import {
  LayoutDashboard,
  Terminal,
  TrendingUp,
  Search,
  FileText,
  Video,
  Image,
  Film,
  Mic,
  Sparkles,
  SearchCheck,
  Repeat,
  Youtube,
  Calendar,
  BarChart3,
  Palette,
  Layers,
  FolderGit2,
  Users,
  Settings,
  Radar,
  Tv,
  PlaySquare,
  Trophy,
  Compass,
  Crosshair,
  Radio,
  Flame,
  Lightbulb,
} from 'lucide-react';
import type { AppRoute, NavItemConfig } from '../types';

export interface RouteMeta extends NavItemConfig {
  icon: typeof LayoutDashboard;
  pipelineStage?: number;
  stageName?: string;
  phaseNote?: string;
}

export const NAV_ITEMS: RouteMeta[] = [
  // Core
  {
    path: '/dashboard',
    label: 'Dashboard',
    category: 'core',
    icon: LayoutDashboard,
    description: 'Central creator command center and operational workspace overview.',
    phase: 'foundation',
  },
  {
    path: '/ai-command',
    label: 'AI Command',
    category: 'core',
    icon: Terminal,
    description: 'Universal creator terminal for natural language command orchestration.',
    phase: 'phase_2',
    phaseNote: 'Command engine standby. Core prompt parser scheduled for Phase 2.',
  },

  // Creative Pipeline (The 17-step creator workflow)
  {
    path: '/trends',
    label: 'Trends',
    category: 'creation',
    icon: TrendingUp,
    pipelineStage: 1,
    stageName: 'Trend Discovery',
    description: 'Cross-platform viral signal radar and topic velocity analyzer.',
    phase: 'phase_2',
    phaseNote: 'Platform scrapers and trend clustering algorithms not connected yet.',
  },
  {
    path: '/research',
    label: 'Research',
    category: 'creation',
    icon: Search,
    pipelineStage: 2,
    stageName: 'Deep Research',
    description: 'Automated citation, competitor gap analysis, and source verification.',
    phase: 'phase_2',
    phaseNote: 'Deep search indexer and knowledge graph integration coming in Phase 2.',
  },
  {
    path: '/ideas',
    label: 'Idea Generator',
    category: 'creation',
    icon: Lightbulb,
    pipelineStage: 3,
    stageName: 'Idea Generation',
    description: 'AI-powered content ideation, scoring, angles, and hook engineering.',
    phase: 'foundation',
  },
  {
    path: '/script',
    label: 'Script Studio',
    category: 'creation',
    icon: FileText,
    pipelineStage: 4,
    stageName: 'Scriptwriting',
    description: 'Hook generation, retention-tuned pacing, scene breakdowns, and multi-format script studio.',
    phase: 'foundation',
  },
  {
    path: '/video-generator',
    label: 'Video Generator',
    category: 'creation',
    icon: Video,
    pipelineStage: 7,
    stageName: 'AI Video Gen',
    description: 'Generative scene synthesizer, camera path control, and text-to-video studio.',
    phase: 'phase_2',
    phaseNote: 'AI video generation not implemented yet. Render pipeline scheduled for future phase.',
  },
  {
    path: '/image-studio',
    label: 'Image Studio',
    category: 'creation',
    icon: Image,
    pipelineStage: 6,
    stageName: 'Visual Studio',
    description: 'High-resolution visual generation, character consistency, and art direction.',
    phase: 'phase_2',
    phaseNote: 'Diffusion pipeline and prompt-to-image engine not connected yet.',
  },
  {
    path: '/editor',
    label: 'Video Editor',
    category: 'creation',
    icon: Film,
    pipelineStage: 9,
    stageName: 'Timeline Editing',
    description: 'Multi-track non-linear browser editor with magnetic timeline and transitions.',
    phase: 'phase_2',
    phaseNote: 'WebAssembly video composition engine scheduled for next development phase.',
  },
  {
    path: '/voice',
    label: 'Voice & Audio',
    category: 'creation',
    icon: Mic,
    pipelineStage: 8,
    stageName: 'Voice & Audio',
    description: 'Neural voice cloning, studio voiceover generation, and background stems.',
    phase: 'phase_2',
    phaseNote: 'TTS audio synthesis and stem separator not connected yet.',
  },
  {
    path: '/thumbnail',
    label: 'Thumbnail Lab',
    category: 'creation',
    icon: Sparkles,
    pipelineStage: 11,
    stageName: 'Thumbnail Lab',
    description: 'High-CTR thumbnail generator, face cutout synthesizer, and A/B test predictor.',
    phase: 'phase_2',
    phaseNote: 'Thumbnail generation and CTR prediction models not connected yet.',
  },

  // Distribution & Optimization
  {
    path: '/seo',
    label: 'SEO Studio',
    category: 'distribution',
    icon: SearchCheck,
    pipelineStage: 12,
    stageName: 'SEO Optimization',
    description: 'Search intent modeling, algorithm tag scoring, and title CTR maximization.',
    phase: 'phase_2',
    phaseNote: 'Metadata scorer and search intent engine not connected yet.',
  },
  {
    path: '/repurpose',
    label: 'Repurpose',
    category: 'distribution',
    icon: Repeat,
    pipelineStage: 13,
    stageName: 'Content Repurpose',
    description: 'Long-form to multi-platform Shorts, Reels, TikTok, and blog post converter.',
    phase: 'phase_2',
    phaseNote: 'Auto-clip timestamp detector not connected yet.',
  },
  {
    path: '/youtube',
    label: 'YouTube Studio',
    category: 'distribution',
    icon: Youtube,
    pipelineStage: 14,
    stageName: 'YouTube Publishing',
    description: 'Direct channel synchronization, automated upload, and chapter management.',
    phase: 'phase_2',
    phaseNote: 'YouTube Data API v3 not connected yet. Connect YouTube integration planned for future phase.',
  },
  {
    path: '/scheduler',
    label: 'Scheduler',
    category: 'distribution',
    icon: Calendar,
    pipelineStage: 15,
    stageName: 'Content Calendar',
    description: 'Multi-timezone broadcast calendar and optimal publishing time calculator.',
    phase: 'phase_2',
    phaseNote: 'Publishing daemon and calendar sync scheduled for next phase.',
  },
  {
    path: '/analytics',
    label: 'Analytics',
    category: 'distribution',
    icon: BarChart3,
    pipelineStage: 16,
    stageName: 'Performance Analytics',
    description: 'Cross-platform audience retention, conversion velocity, and ROI diagnostics.',
    phase: 'phase_2',
    phaseNote: 'Telemetry aggregation pipelines not connected yet.',
  },

  // Management & Setup
  {
    path: '/brand',
    label: 'Brand Kit',
    category: 'management',
    icon: Palette,
    description: 'Typography tokens, color palettes, watermark presets, and voice guidelines.',
    phase: 'phase_2',
    phaseNote: 'Brand asset persistence and preset injector scheduled for next phase.',
  },
  {
    path: '/templates',
    label: 'Templates',
    category: 'management',
    icon: Layers,
    description: 'Pre-configured workflow blueprints and viral video formula structures.',
    phase: 'phase_2',
    phaseNote: 'Template library and blueprint loader not connected yet.',
  },
  {
    path: '/projects',
    label: 'Projects',
    category: 'management',
    icon: FolderGit2,
    description: 'Manage creator project workspaces, folders, and local storage state.',
    phase: 'foundation',
  },
  {
    path: '/team',
    label: 'Team',
    category: 'management',
    icon: Users,
    description: 'Role-based access, editor assignment, and approval workflows.',
    phase: 'phase_2',
    phaseNote: 'Multi-user collaboration and team roles scheduled for next phase.',
  },
  {
    path: '/settings',
    label: 'Settings',
    category: 'management',
    icon: Settings,
    description: 'Theme preferences, language, connected services, and system engine diagnostics.',
    phase: 'foundation',
  },

  // YouTube Intelligence
  {
    path: '/youtube-intelligence',
    label: 'Intelligence Dashboard',
    category: 'intelligence',
    icon: Radar,
    description: 'Central YouTube macro intelligence radar and channel opportunity overview.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/channel',
    label: 'Channel Analyzer',
    category: 'intelligence',
    icon: Tv,
    description: 'Deep dive channel audits, upload cadence, and viewer conversion metrics.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/video',
    label: 'Video Analyzer',
    category: 'intelligence',
    icon: PlaySquare,
    description: 'Single video performance velocity, title/thumbnail diagnostics, and pacing.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/rankings',
    label: 'Rankings',
    category: 'intelligence',
    icon: Trophy,
    description: 'Global and regional creator leaderboards across categories and time horizons.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/topics',
    label: 'Topic Radar',
    category: 'intelligence',
    icon: Compass,
    description: 'Emerging content demand clusters and creator opportunity scoring.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/competitors',
    label: 'Competitor Radar',
    category: 'intelligence',
    icon: Crosshair,
    description: 'Track peer creators, compare upload frequency, and identify audience overlap.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/live',
    label: 'Live Radar',
    category: 'intelligence',
    icon: Radio,
    description: 'Real-time live streaming signals, concurrent viewers, and chat velocity.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/outliers',
    label: 'Outlier Detector',
    category: 'intelligence',
    icon: Flame,
    description: 'Statistical anomaly detector isolating breakout videos exceeding channel averages.',
    phase: 'foundation',
  },
  {
    path: '/youtube-intelligence/strategy',
    label: 'Strategy Analyzer',
    category: 'intelligence',
    icon: Lightbulb,
    description: 'Extract market patterns to architect your original, high-retention content roadmap.',
    phase: 'foundation',
  },
];

export const PIPELINE_STEPS = [
  'Trend',
  'Research',
  'Idea',
  'Script',
  'Story',
  'Image',
  'Video',
  'Voice',
  'Editing',
  'Captions',
  'Thumbnail',
  'SEO',
  'Repurpose',
  'YouTube',
  'Schedule',
  'Analytics',
];
