import { StoryModeConfig } from '../../types';

export const STORY_MODES: StoryModeConfig[] = [
  {
    id: 'sci-fi',
    name: 'Sci-Fi',
    category: 'Cinematic',
    description: 'Speculative cosmic reality examining technological boundaries and astrophysics anomalies.',
    tone: 'Analytical, awe-inspiring, intellectually intense',
    pacing: 'Measured with sudden explosive revelation beats',
    visualStyle: 'High-contrast stark neon against absolute void, lens flare diffraction, optical telemetry overlays',
    cameraStyle: 'Deliberate orbital dollies, wide cosmological establishing frames, slow push-ins',
    voiceStyle: 'Calm, authoritative, existential, precision-cadenced',
    musicStyle: 'Deep sub-bass analog synthesizers, crystalline polyphonic pads, gravitational hums',
    sceneDensity: 'Moderate',
    targetTone: 'Existential Wonder',
    atmosphere: 'Deep Space Pressure',
    tags: ['Space', 'Quantum', 'Cosmic Horror', 'Astrophysics'],
  },
  {
    id: 'space',
    name: 'Space',
    category: 'Cinematic',
    description: 'Direct deep void expeditions highlighting extreme survival, stellar phenomena, and celestial scale.',
    tone: 'Sublime, silent, terrifyingly vast',
    pacing: 'Steady atmospheric drift punctuated by critical failure sequences',
    visualStyle: 'Absolute black viewport backgrounds, harsh directional solar illumination, volumetric thruster exhausts',
    cameraStyle: 'Weightless floating handheld drift, panoramic planetary sweeps',
    voiceStyle: 'Radio-filtered headset communications, measured breathing, calm protocol delivery',
    musicStyle: 'Isolated sub-frequencies, droning metallic harmonics, silence as a percussive instrument',
    sceneDensity: 'Sparse',
    targetTone: 'Vast Isolation',
    atmosphere: 'Zero-G Vacuum',
    tags: ['Astronautics', 'Orbital', 'Black Hole', 'Deep Space'],
  },
  {
    id: 'documentary',
    name: 'Documentary',
    category: 'Documentary',
    description: 'Empirical investigative inquiry presenting undeniable evidence, archival logs, and chronological breakthroughs.',
    tone: 'Objective, journalistic, investigative, urgent',
    pacing: 'Methodical evidentiary escalation with revelatory crescendos',
    visualStyle: 'Macro camera realism, forensic archival textures, telemetry graphic overlays, authentic lighting',
    cameraStyle: 'Observational steadycam, medium contextual framing, slow archival zooms',
    voiceStyle: 'Grounded, nuanced, authoritative, journalistic',
    musicStyle: 'Minimalist acoustic piano patterns, pulsing rhythmic cellos, subtle electronic tension',
    sceneDensity: 'Moderate',
    targetTone: 'Forensic Rigor',
    atmosphere: 'Archival Vault',
    tags: ['Investigative', 'Archival', 'Truth', 'Chronological'],
  },
  {
    id: 'mystery',
    name: 'Mystery',
    category: 'Narrative',
    description: 'Cryptic puzzle narratives driven by withheld revelations, anomalous clues, and deductive tension.',
    tone: 'Suspicious, enigmatic, calculating, veiled',
    pacing: 'Tension curve tightening with each discovered breadcrumb',
    visualStyle: 'Obscured silhouettes, heavy shadow falloff, low-key lighting, shallow depth of field',
    cameraStyle: 'Over-the-shoulder voyeuristic tracking, selective rack focuses on forensic details',
    voiceStyle: 'Intimate, cautious, inquisitive, whispered implications',
    musicStyle: 'Dissonant bowed strings, ticking clock motifs, unresolved microtonal textures',
    sceneDensity: 'Moderate',
    targetTone: 'Paranoid Inquiry',
    atmosphere: 'Veiled Shadows',
    tags: ['Cipher', 'Enigma', 'Secret', 'Detective'],
  },
  {
    id: 'thriller',
    name: 'Thriller',
    category: 'Narrative',
    description: 'High-stakes psychological and physical peril with uncompromising ticking-clock momentum.',
    tone: 'Breathless, adrenaline-fueled, claustrophobic',
    pacing: 'Rapidly accelerating beats with relentless pressure',
    visualStyle: 'Desaturated cold tones with acute warm danger accents, rapid shutter motion blur',
    cameraStyle: 'Frantic kinetic steadycam, dutch tilt angles, intense macro close-ups',
    voiceStyle: 'Urgent, terse, heart-rate synchronous cadence',
    musicStyle: 'Heartbeat sub-percussion, accelerating tempo ostinatos, shearing industrial synthesis',
    sceneDensity: 'Kinetic',
    targetTone: 'Relentless Peril',
    atmosphere: 'High Pressure',
    tags: ['Countdown', 'Suspense', 'Stakes', 'Tension'],
  },
  {
    id: 'psychological',
    name: 'Psychological',
    category: 'Narrative',
    description: 'Internal cognitive distortion blurring the threshold between objective reality and delusion.',
    tone: 'Unsettling, disorienting, haunting, introspective',
    pacing: 'Hypnotic, dreamlike shifts that collapse suddenly into sharp paranoia',
    visualStyle: 'Mirrored surfaces, distorted lens optics, chromatic aberration, flickering light sources',
    cameraStyle: 'Slow claustrophobic rotations, disorienting framing, stationary unblinking stares',
    voiceStyle: 'Fragmented interior monologues, eerie spatial panning, second-person direct address',
    musicStyle: 'Binaural droning frequencies, warped acoustic instruments, reverse tape echoes',
    sceneDensity: 'Moderate',
    targetTone: 'Perceptual Fracture',
    atmosphere: 'Labyrinth Mind',
    tags: ['Mind', 'Perception', 'Introspection', 'Illusion'],
  },
  {
    id: 'action',
    name: 'Action',
    category: 'Cinematic',
    description: 'Visceral physical conflict, kinetic choreography, and high-impact explosive sequences.',
    tone: 'Dynamic, triumphant, bold, kinetic',
    pacing: 'Blistering, high-impact bursts alternating with sharp breathers',
    visualStyle: 'Vibrant punchy contrast, dynamic rim lights, practical particle sprays and lens dust',
    cameraStyle: 'Dynamic whip-pans, hyper-kinetic drone paths, tracking collision shots',
    voiceStyle: 'Commanding, forceful, rhythmic, decisive',
    musicStyle: 'Massive orchestral percussion, driving synthesized basslines, brass fanfares',
    sceneDensity: 'Kinetic',
    targetTone: 'Peak Velocity',
    atmosphere: 'Combat Zone',
    tags: ['Combat', 'Velocity', 'Choreography', 'Impact'],
  },
  {
    id: 'crime',
    name: 'Crime',
    category: 'Narrative',
    description: 'Underworld hierarchies, procedural investigations, moral ambiguity, and calculated gambits.',
    tone: 'Gritty, cynical, sharp, uncompromising',
    pacing: 'Calculated procedural buildup leading to ruthless executions',
    visualStyle: 'Wet asphalt reflections, sodium-vapor streetlamps, harsh fluorescent interrogation light',
    cameraStyle: 'Static stakeout surveillance perspectives, slow predatory dollies',
    voiceStyle: 'Deadpan, gravelly, cynical, weary realism',
    musicStyle: 'Blues-tinged low brass, muffled jazz percussion, electric bass grooves',
    sceneDensity: 'Moderate',
    targetTone: 'Moral Ambiguity',
    atmosphere: 'Noir Underbelly',
    tags: ['Underworld', 'Procedural', 'Heist', 'Investigation'],
  },
  {
    id: 'horror',
    name: 'Horror',
    category: 'Genre',
    description: 'Primal dread, visceral vulnerability, cosmic incomprehension, and predatory malice.',
    tone: 'Terrifying, suffocating, visceral, inescapable',
    pacing: 'Agonizing sustained dread punctuated by jarring sonic shocks',
    visualStyle: 'Stifling negative space, pitch-black voids, sickly greenish-yellow hues, vignetting',
    cameraStyle: 'Creeping unseen observer perspectives, locked static frames where monsters approach',
    voiceStyle: 'Ragged gasps, suppressed weeping, rasping otherworldly frequencies',
    musicStyle: 'Atonal string screeches, infrasound rumbles below 20Hz, sudden silence dropouts',
    sceneDensity: 'Sparse',
    targetTone: 'Visceral Dread',
    atmosphere: 'Suffocating Dark',
    tags: ['Cosmic Horror', 'Survival', 'Dread', 'Monsters'],
  },
  {
    id: 'investigation',
    name: 'Investigation',
    category: 'Informational',
    description: 'Step-by-step forensic deduction dissecting evidence, motive, timelines, and hidden links.',
    tone: 'Methodical, forensic, piercing, clear-eyed',
    pacing: 'Steady intellectual assembly of disparate data nodes',
    visualStyle: 'High-definition data visualizers, corkboard node-linking lines, forensic magnifying perspectives',
    cameraStyle: 'Smooth lateral slider passes across documents, symmetrical overhead tabletop frames',
    voiceStyle: 'Analytical, precise, questioning, articulating deductive connections',
    musicStyle: 'Polyrhythmic synth arpeggios, crisp clockwork hi-hats, subtle bass pulses',
    sceneDensity: 'Moderate',
    targetTone: 'Deductive Clarity',
    atmosphere: 'War Room Desk',
    tags: ['Forensic', 'Deduction', 'Clues', 'Evidence'],
  },
  {
    id: 'adventure',
    name: 'Adventure',
    category: 'Cinematic',
    description: 'Expeditions into uncharted frontiers, mythical relics, and exhilarating navigational trials.',
    tone: 'Exhilarating, spirited, bold, wondrous',
    pacing: 'Brisk continuous journey forward across escalating landscapes',
    visualStyle: 'Golden-hour warm sunlight, epic scale vistas, elemental weather contrasts',
    cameraStyle: 'Sweeping crane shots over mountain ridges, dynamic forward tracking runs',
    voiceStyle: 'Enthusiastic, bold, inspiring, storytelling-rich',
    musicStyle: 'Soaring French horns, orchestral strings, triumphant adventure anthems',
    sceneDensity: 'Moderate',
    targetTone: 'Epic Journey',
    atmosphere: 'Uncharted Wilds',
    tags: ['Frontier', 'Discovery', 'Expedition', 'Odyssey'],
  },
  {
    id: 'survival',
    name: 'Survival',
    category: 'Narrative',
    description: 'Human endurance tested against hostile environments, resource scarcity, and nature’s fury.',
    tone: 'Grim, primal, resilient, visceral',
    pacing: 'Exhausting physical attrition with brief desperate triumphs',
    visualStyle: 'Weather-beaten lens droplets, frost accretion, desaturated survival landscape palettes',
    cameraStyle: 'Intimate handheld following heavy footsteps, ground-level POV looking upward',
    voiceStyle: 'Hoarse, strained, economical, concentrated on immediate physical action',
    musicStyle: 'Sparse acoustic cello, wind droning textures, heartbeat rhythmic thumps',
    sceneDensity: 'Sparse',
    targetTone: 'Primal Endurance',
    atmosphere: 'Hostile Element',
    tags: ['Endurance', 'Hostile Environment', 'Scarcity', 'Grit'],
  },
  {
    id: 'fantasy',
    name: 'Fantasy',
    category: 'Genre',
    description: 'Ancient magical lore, mythical civilizations, prophecies, and supernatural forces.',
    tone: 'Mythic, grand, enchanting, timeless',
    pacing: 'Episodic majestic world unfolds toward apocalyptic magical clashes',
    visualStyle: 'Luminous magical ether glows, ornate architectural silhouettes, ethereal twilight palettes',
    cameraStyle: 'Floating ethereal camera moves, monumental vertical tilt-ups to colossal spires',
    voiceStyle: 'Poetic, solemn, lyrical, carrying ancient weight',
    musicStyle: 'Celtic harps, choral chants in fictional dialects, massive brass and orchestral swells',
    sceneDensity: 'High',
    targetTone: 'Mythic Grandeur',
    atmosphere: 'Enchanted Realm',
    tags: ['Magic', 'Mythology', 'Colossal Lore', 'Prophecy'],
  },
  {
    id: 'romance',
    name: 'Romance',
    category: 'Narrative',
    description: 'Emotional vulnerability, interpersonal gravity, longing, and transformative human bonds.',
    tone: 'Intimate, passionate, tender, bittersweet',
    pacing: 'Lyrical emotional rhythms giving space to gaze, dialogue, and hesitation',
    visualStyle: 'Soft diffused backlight, warm amber candlelight, dreamy bokeh circles, rich skin tones',
    cameraStyle: 'Gentle intimate two-shots, slow pushes into expressive eyes, lyrical pans',
    voiceStyle: 'Soft, vulnerable, nuanced with subtext and emotional inflection',
    musicStyle: 'Emotive acoustic piano, solo violin melodies, warm lush orchestral strings',
    sceneDensity: 'Sparse',
    targetTone: 'Emotional Gravity',
    atmosphere: 'Warm Intimacy',
    tags: ['Love', 'Longing', 'Connection', 'Intimacy'],
  },
  {
    id: 'comedy',
    name: 'Comedy',
    category: 'Narrative',
    description: 'Subverted expectations, sharp timing, witty banter, and situational absurdity.',
    tone: 'Playful, irreverent, sharp, energetic',
    pacing: 'Brisk, rhythmic, calibrated precisely to comedic setup and punchline pauses',
    visualStyle: 'Bright, saturated, high-key lighting, clear readable staging allowing physical comedy',
    cameraStyle: 'Snap zooms for comedic reactions, wide contextual masters for staging irony',
    voiceStyle: 'Vibrant, expressive, dynamic inflection with pinpoint comedic timing',
    musicStyle: 'Bouncy acoustic upright bass, playful brass stabs, quirky melodic motifs',
    sceneDensity: 'High',
    targetTone: 'Witty Levity',
    atmosphere: 'Vibrant Energy',
    tags: ['Satire', 'Banter', 'Irony', 'Timing'],
  },
  {
    id: 'drama',
    name: 'Drama',
    category: 'Narrative',
    description: 'Profound character study, moral dilemmas, conflicting values, and authentic tragedy.',
    tone: 'Raw, honest, emotionally devastating, cathartic',
    pacing: 'Deliberate, allowing heavy silences and emotional confrontations to breathe',
    visualStyle: 'Naturalistic directional lighting, rich textured shadows, desaturated realistic palette',
    cameraStyle: 'Patient static framing, subtle slow zooms into characters grappling with truth',
    voiceStyle: 'Emotionally authentic, restrained grief or conflict, conversational authenticity',
    musicStyle: 'Solo acoustic instruments, melancholic strings, delicate ambient harmonic beds',
    sceneDensity: 'Moderate',
    targetTone: 'Deep Catharsis',
    atmosphere: 'Quiet Reality',
    tags: ['Character Study', 'Conflict', 'Catharsis', 'Realism'],
  },
  {
    id: 'historical',
    name: 'Historical',
    category: 'Documentary',
    description: 'Accurate chronological reconstruction of monumental eras, revolutions, and historical turning points.',
    tone: 'Epochal, dignified, scholarly, monumental',
    pacing: 'Measured historical march from geopolitical triggers to tectonic global outcomes',
    visualStyle: 'Period-accurate color grading, vintage film grain, sepia-burnished warm metallics',
    cameraStyle: 'Classical stable cinema composition, wide battle lines, stately interior tracks',
    voiceStyle: 'Stately, measured, historically grounded, articulate',
    musicStyle: 'Period-authentic instrumentation, somber martial percussion, epic classical movements',
    sceneDensity: 'Moderate',
    targetTone: 'Epochal Weight',
    atmosphere: 'Hall of History',
    tags: ['Epoch', 'Period', 'Reconstruction', 'Dynasty'],
  },
  {
    id: 'biography',
    name: 'Biography',
    category: 'Documentary',
    description: 'Intimate life trajectory of a transformative pioneer, icon, villain, or visionary mind.',
    tone: 'Empathetic, introspective, revelatory, illuminating',
    pacing: 'Chronological milestone leaps anchored by intimate personal decisions',
    visualStyle: 'Portrait lighting, personal artifact close-ups, handwritten manuscript textures',
    cameraStyle: 'Intimate portrait framing, tracking alongside the subject as they walk through memory',
    voiceStyle: 'Reflective, deeply personal, observant, compassionate',
    musicStyle: 'Nostalgic acoustic piano, gentle woodwinds, evolving thematic leitmotifs',
    sceneDensity: 'Moderate',
    targetTone: 'Human Legacy',
    atmosphere: 'Personal Archive',
    tags: ['Pioneer', 'Legacy', 'Intimate', 'Memoir'],
  },
  {
    id: 'news',
    name: 'News',
    category: 'Informational',
    description: 'Real-time breaking dispatch delivering high-urgency updates, verified facts, and immediate analysis.',
    tone: 'Urgent, objective, crisp, authoritative',
    pacing: 'Rapid-fire, bulleted, relentless momentum',
    visualStyle: 'Split screens, live satellite feeds, bold lower-thirds, graphic telemetry tickers',
    cameraStyle: 'Direct-to-camera eye-level framing, fast pan transitions, responsive broadcast angles',
    voiceStyle: 'Clear, rapid, articulate, broadcast-standard cadence',
    musicStyle: 'Urgent rhythmic broadcast synths, driving digital marimbas, authoritative stingers',
    sceneDensity: 'Kinetic',
    targetTone: 'Urgent Factuality',
    atmosphere: 'Live Newsroom',
    tags: ['Breaking', 'Urgent', 'Broadcast', 'Dispatch'],
  },
  {
    id: 'explainer',
    name: 'Explainer',
    category: 'Informational',
    description: 'Deconstructing complex concepts, systems, and paradoxes into crystal-clear intuitive models.',
    tone: 'Engaging, clarifying, lucid, inspiring',
    pacing: 'Step-by-step sequential clarity with frequent visual payoff moments',
    visualStyle: 'Clean vector schematics, 3D animated model breakdowns, crisp graphic annotations',
    cameraStyle: 'Dynamic graphic zooms, isometric rotations around 3D diagrams, screen-screen pans',
    voiceStyle: 'Warm, enthusiastic, lucid, conversational pedagogue',
    musicStyle: 'Inspiring modern minimalist electronics, cheerful synth plucks, driving acoustic guitar pulses',
    sceneDensity: 'High',
    targetTone: 'Intuitive Light',
    atmosphere: 'Digital Academy',
    tags: ['Concept Breakdown', 'Pedagogy', 'System', 'Diagrams'],
  },
  {
    id: 'educational',
    name: 'Educational',
    category: 'Informational',
    description: 'Rigorous deep-dive pedagogy providing foundational mastery, scientific rigor, and academic depth.',
    tone: 'Scholarly, patient, systematic, illuminating',
    pacing: 'Gradual concept scaffolding from fundamentals to edge-case mastery',
    visualStyle: 'Chalkboard mathematics, laboratory instruments, empirical graphs and charts',
    cameraStyle: 'Stable centered framing on educational assets, clear illustrative cuts',
    voiceStyle: 'Measured, reassuring, patient, articulate',
    musicStyle: 'Gentle ambient study synth, warm neoclassical piano, non-intrusive focus frequencies',
    sceneDensity: 'Moderate',
    targetTone: 'Scholarly Rigor',
    atmosphere: 'Cosmic Laboratory',
    tags: ['Science', 'Scaffolding', 'Pedagogy', 'Mastery'],
  },
  {
    id: 'travel',
    name: 'Travel',
    category: 'Documentary',
    description: 'Sensory immersion in foreign geographies, cultural rituals, alien vistas, and nomadic journeys.',
    tone: 'Sensory, vibrant, nomadic, awe-filled',
    pacing: 'Breezy exploration with lingering cultural immersion pauses',
    visualStyle: 'Lush saturated local color palettes, natural golden hour sunlight, architectural detail',
    cameraStyle: 'Fluid gliding gimbal shots moving through crowded bazaars and natural panoramas',
    voiceStyle: 'Curious, conversational, poetic, evocative',
    musicStyle: 'Authentic regional acoustic instruments blended with modern ambient house pulses',
    sceneDensity: 'Moderate',
    targetTone: 'Wanderlust',
    atmosphere: 'Alien Horizon',
    tags: ['Culture', 'Landscape', 'Sensory', 'Expedition'],
  },
  {
    id: 'gaming',
    name: 'Gaming',
    category: 'Cinematic',
    description: 'High-octane interactive combat, tactical analysis, speedrun records, and virtual realm lore.',
    tone: 'Electric, hype-driven, tactical, immersed',
    pacing: 'Hypersonic montage editing synced to beat drops and clutch victory moments',
    visualStyle: 'Ultra-high framerate crispness, RGB neon accents, HUD overlay elements, glitch wipes',
    cameraStyle: 'Virtual in-engine free-camera tracking, 360-degree rotational spin moves, impact zooms',
    voiceStyle: 'Hyped, energetic, reactive, insider vocabulary',
    musicStyle: 'Dubstep drops, synthwave arpeggios, aggressive glitch-hop drum kits',
    sceneDensity: 'Kinetic',
    targetTone: 'Clutch Adrenaline',
    atmosphere: 'Cyber Arena',
    tags: ['Virtual', 'Clutch', 'Esports', 'Montage'],
  },
  {
    id: 'technology',
    name: 'Technology',
    category: 'Informational',
    description: 'Frontier AI, quantum computing, robotics, and cybernetic architectures reshaping the species.',
    tone: 'Futuristic, precise, speculative, razor-sharp',
    pacing: 'Crisp, accelerating, punctuated by radical milestone paradigm shifts',
    visualStyle: 'Silicon wafer macro photography, glowing server racks, holographic blueprints, wireframe renders',
    cameraStyle: 'Precision robotic slider movements, microscopic macro lens tracking inside microchips',
    voiceStyle: 'Intellectually commanding, forward-looking, analytical, vision-casting',
    musicStyle: 'Glitched IDM rhythms, precise modular synth bleeps, deep technological bass pulses',
    sceneDensity: 'High',
    targetTone: 'Frontier Breakthrough',
    atmosphere: 'Quantum Foundry',
    tags: ['AI', 'Quantum', 'Cybernetics', 'Frontier'],
  },
  {
    id: 'sports',
    name: 'Sports',
    category: 'Cinematic',
    description: 'Human athletic peak performance, underdog resilience, tactical championship moments.',
    tone: 'Inspiring, ferocious, emotional, triumphant',
    pacing: 'Building pressure culminating in clutch final-second climaxes',
    visualStyle: 'Super slow-motion 1000fps sweat droplets, stadium floodlight flares, intense eye focuses',
    cameraStyle: 'Low-angle hero perspective tracking alongside sprinting athletes, sideline pans',
    voiceStyle: 'Booming, passionate, dramatic sports broadcast narrative',
    musicStyle: 'Thunderous taiko drums, rising brass fanfares, stadium rock energy',
    sceneDensity: 'Kinetic',
    targetTone: 'Championship Triumph',
    atmosphere: 'Colosseum Arena',
    tags: ['Athletics', 'Clutch', 'Underdog', 'Glory'],
  },
  {
    id: 'war-history',
    name: 'War History',
    category: 'Documentary',
    description: 'Strategic battlefield breakdowns, geopolitical collisions, tactical maps, and combat diaries.',
    tone: 'Somber, strategic, harrowing, monumental',
    pacing: 'Strategic campaign maps alternating with visceral frontline chaos',
    visualStyle: 'Animated 3D topographical tactical maps, smoke and embers particles, desaturated trench tones',
    cameraStyle: 'Overhead bird’s-eye tactical projections, shaky combat documentary camera angles',
    voiceStyle: 'Grave, authoritative, deeply respectful, tactically insightful',
    musicStyle: 'Solemn snare drums, sorrowful bagpipes and low cellos, booming artillery echoes',
    sceneDensity: 'Moderate',
    targetTone: 'Strategic Sacrifice',
    atmosphere: 'Command Bunker',
    tags: ['Tactical', 'Battlefield', 'Strategy', 'History'],
  },
  {
    id: 'post-apocalyptic',
    name: 'Post-Apocalyptic',
    category: 'Genre',
    description: 'Civilizational ruin, mutated biospheres, scavenged remnants, and bitter survival in the ash.',
    tone: 'Desolate, haunting, gritty, stubbornly hopeful',
    pacing: 'Bleak wandering interrupted by sudden territorial ambushes and discovery of relics',
    visualStyle: 'Rust and dust ochre color palettes, overgrown ruins of skyscrapers, harsh irradiated sunlight',
    cameraStyle: 'Wide desolate panoramic dollies, handheld wandering through rusted debris',
    voiceStyle: 'Raspy, weary, weathered, pragmatic survivalist monologue',
    musicStyle: 'Distant acoustic slide guitar, ambient Geiger counter clicks, industrial scrap metal clangs',
    sceneDensity: 'Sparse',
    targetTone: 'Ashen Solitude',
    atmosphere: 'Sunken Ruins',
    tags: ['Scavenger', 'Wasteland', 'Fall of Man', 'Rust'],
  },
];

export function getStoryModeConfig(id: string): StoryModeConfig {
  const found = STORY_MODES.find((m) => m.id.toLowerCase() === id.toLowerCase());
  return found || STORY_MODES[0];
}

export interface FusedStoryStyle {
  primary: StoryModeConfig;
  secondary: StoryModeConfig;
  fusionScore: number;
  fusedTone: string;
  fusedPacing: string;
  fusedVisualStyle: string;
  fusedCameraStyle: string;
  fusedVoiceStyle: string;
  fusedMusicStyle: string;
}

export function computeStoryModeFusion(primaryId: string, secondaryId: string): FusedStoryStyle {
  const primary = getStoryModeConfig(primaryId);
  const secondary = getStoryModeConfig(secondaryId);

  // Compute deterministic algorithmic harmonic score based on character traits
  const charSum = (primary.name.length * 13 + secondary.name.length * 17) % 15;
  const fusionScore = 85 + charSum;

  return {
    primary,
    secondary,
    fusionScore,
    fusedTone: `${primary.tone || primary.targetTone} fused with ${(secondary.tone || secondary.targetTone).toLowerCase()}`,
    fusedPacing: `${primary.pacing}, accented by ${secondary.pacing.toLowerCase()}`,
    fusedVisualStyle: `${primary.visualStyle || primary.atmosphere}; subtly balanced with ${(secondary.visualStyle || secondary.atmosphere).toLowerCase()}`,
    fusedCameraStyle: `${primary.cameraStyle || 'Cinematic Optic'} shifting into ${(secondary.cameraStyle || 'Dynamic Tracking').toLowerCase()}`,
    fusedVoiceStyle: `${primary.voiceStyle || 'Measured'} with elements of ${(secondary.voiceStyle || 'Atmospheric').toLowerCase()}`,
    fusedMusicStyle: `${primary.musicStyle || 'Ambient Synth'} infused with ${(secondary.musicStyle || 'Orchestral').toLowerCase()}`,
  };
}
