import type { StoryMode, StoryModeProfile } from '../types/storyMode';

export const STORY_MODE_PROFILES: Record<StoryMode, StoryModeProfile> = {
  Documentary: {
    id: 'Documentary',
    label: 'Documentary',
    category: 'Informative',
    description: 'Immersive reality-driven investigation with authentic archival depth, observational pacing, and thought-provoking inquiry.',
    narrativeStructure: 'Historical/observational opening hook, investigative timeline progression, firsthand perspectives/evidence, overarching cultural or existential synthesis.',
    pacing: 'moderate',
    hookStyle: 'Profound archival fact, unseen footage premise, or paradigm-shifting real-world question.',
    narrationStyle: 'Measured, authoritative, introspective, grounded in journalistic rigor.',
    visualStyle: 'High-grain archival footage, anamorphic landscape b-roll, clean minimalist graphic overlays.',
    cameraStyle: 'Handheld observational tracking, slow cinematic push-ins, wide environmental plates.',
    lightingStyle: 'Naturalistic ambient lighting, soft directional window light, subdued documentary contrast.',
    musicDirection: 'Atmospheric strings, ambient minimalist piano, evolving textural drones.',
    soundDirection: 'Rich organic diegetic audio, room tone, crisp archival audio crackle, subtle field recordings.',
    sceneDensity: 'medium',
    transitionStyle: 'Slow match cuts, hard cuts to archival stills, filmic cross-dissolves.',
    captionStyle: 'Clean white sans-serif sub, subtle dark backing, journalistic typography.',
    thumbnailDirection: 'High-contrast real-world subject close-up with authentic documentary texture and investigative banner.',
    titleDirection: 'The Untold Story of / Inside The Secret History of / What Really Happened to',
    shortFormAdjustment: 'Lead with an unbelievable verified real-world fact in 2 seconds, rapid evidence montage, immediate philosophical punchline.',
    longFormAdjustment: 'Expansive thematic acts, deep-dive archival chapters, multi-source interview cadence.',
  },

  Action: {
    id: 'Action',
    label: 'Action',
    category: 'Genre',
    description: 'High-octane kinetic propulsion, physical stakes, rapid set-piece sequences, and relentless momentum.',
    narrativeStructure: 'In media res cold open, accelerating obstacle chain, decisive escalation, explosive climax.',
    pacing: 'rapid',
    hookStyle: 'Immediate high-stakes visual crisis or physical danger countdown.',
    narrationStyle: 'Urgent, punchy, adrenaline-fueled, commanding vocal cadence.',
    visualStyle: 'Fast-paced motion blur, intense contrast, dynamic color grading with fiery oranges and cold teals.',
    cameraStyle: 'Shaky cam, low-angle whip pans, rapid tracking zoom, snap zooms on impact.',
    lightingStyle: 'Hard edge lights, dynamic flash strobe effects, high dynamic range highlights.',
    musicDirection: 'Driving percussion, heavy 808 sub-booms, aggressive hybrid orchestral-synth pulses.',
    soundDirection: 'Impact risers, whoosh hits, gunshots/engines/explosive transients, sharp foley.',
    sceneDensity: 'high',
    transitionStyle: 'Speed ramps, whip transitions, flash cuts, glitch impacts.',
    captionStyle: 'Bold punch pop typography, dynamic word-by-word tracking, energetic color highlights.',
    thumbnailDirection: 'High-motion action snapshot, fire/smoke rim light, facial expression of intense adrenaline.',
    titleDirection: 'I Tested The Most Dangerous / Can Anyone Survive / Ultimate High-Stakes',
    shortFormAdjustment: 'Instant motion hook within 0.5s, rapid cuts every 1-2s, non-stop physical escalation to finish.',
    longFormAdjustment: 'Structured set-piece rhythm with brief tactical breathers before escalating set-pieces.',
  },

  Crime: {
    id: 'Crime',
    label: 'Crime',
    category: 'Narrative',
    description: 'Methodical forensic inquiry, criminal underworld motives, police tape revelations, and chilling moral ambiguity.',
    narrativeStructure: 'Cold-open incident or 911 dispatch, crime scene breakdown, motive examination, forensic twists, unresolved mystery or verdict.',
    pacing: 'slow_burn',
    hookStyle: 'Chilling 911 dispatch snippet, surveillance timestamp, or eerie forensic quote.',
    narrationStyle: 'Gravelly, serious, deliberate, analytical, tinged with dark intrigue.',
    visualStyle: 'Desaturated noir tones, police evidence binders, surveillance camera overlays, red-string investigation boards.',
    cameraStyle: 'Slow creeping hallway dollies, high-angle surveillance perspective, locked-off evidence close-ups.',
    lightingStyle: 'Deep shadow chiaroscuro, harsh interrogation lamps, muted rainy exterior neon.',
    musicDirection: 'Low cello drones, metallic percussion ticks, dark synthetic tension pulses.',
    soundDirection: 'Heartbeats, ticking clock foley, audio distortion, distant sirens, heavy breathing.',
    sceneDensity: 'medium',
    transitionStyle: 'Flashbulb white cuts, tape rewinds, desaturated wipe cuts.',
    captionStyle: 'Cyber neon red or stark typewriter monospaced text.',
    thumbnailDirection: 'Redacted evidence folder, mugshot spotlight, shadowy silhouette with glowing red accent.',
    titleDirection: 'The Case That Shocked / The Killer Who Disappeared / The Crime No One Could Solve',
    shortFormAdjustment: 'Eerie evidence snippet in 1s, chronological 45-second micro-timeline, haunting closing question.',
    longFormAdjustment: 'Step-by-step case breakdown, forensic autopsy analysis, timeline reconstructions.',
  },

  Thriller: {
    id: 'Thriller',
    label: 'Thriller',
    category: 'Genre',
    description: 'Suspense-laden psychological pressure cooker with rising stakes, ticking clocks, and destabilizing plot twists.',
    narrativeStructure: 'Impending doom hook, tightening trap or paranoia cycle, false sanctuary, explosive revelation twist.',
    pacing: 'fast',
    hookStyle: 'A countdown to catastrophe or an inescapable psychological trap statement.',
    narrationStyle: 'Tense, breathless, sharp, calculated, heightening audience anxiety.',
    visualStyle: 'Cool desaturated hues, sharp shadows, dutch angles, claustrophobic framing.',
    cameraStyle: 'Vertigo zolly shots, tight handheld framing on trembling hands, erratic pans.',
    lightingStyle: 'Flickering fluorescent tubes, sharp backlighting, slivers of light across eyes.',
    musicDirection: 'Rising Shepard tones, rhythmic heartbeat thuds, dissonant high strings.',
    soundDirection: 'Sub-bass thuds, sudden silence drop-outs, amplified whispers, metallic scrapes.',
    sceneDensity: 'high',
    transitionStyle: 'Hard smash cuts to black, audio J-cuts of breathing, jump cuts.',
    captionStyle: 'Stark uppercase typography, vibrating tension text, flashing key keywords.',
    thumbnailDirection: 'Wide panic eyes, ticking clock or shadow encroaching, high contrast vignette.',
    titleDirection: 'Whatever You Do, Don\'t / The 60-Second Mistake That Ruins Everything / When It All Went Wrong',
    shortFormAdjustment: 'Immediate hook + rapid escalation + payoff within 30-45 seconds.',
    longFormAdjustment: 'Slow suspense build with cascading micro-cliffhangers before the central turning point.',
  },

  Horror: {
    id: 'Horror',
    label: 'Horror',
    category: 'Genre',
    description: 'Visceral dread, psychological terror, uncanny atmosphere, and shocking supernatural or psychological payoffs.',
    narrativeStructure: 'Eerie deceptive tranquility, subtle uncanny anomaly, creeping dread escalation, terrifying confrontation.',
    pacing: 'slow_burn',
    hookStyle: 'A whisper from an empty room or an impossible anomaly captured on camera.',
    narrationStyle: 'Hushed, chilling whisper-register, deeply ominous, unsettling pacing.',
    visualStyle: 'Pitch black crushed shadows, sickening greenish tint, infrared night-vision noise.',
    cameraStyle: 'Lingering static wide shots where something moves in background, sudden unmotivated zooms.',
    lightingStyle: 'Single flashlight beam cutting darkness, flickering emergency lamps, negative space silhouette.',
    musicDirection: 'Distorted nursery rhymes, waterphone screeches, low sub-harmonic vibrations.',
    soundDirection: 'Floorboard creaks, wet guttural clicks, sudden ear-piercing jump hits followed by dead silence.',
    sceneDensity: 'cinematic_sparse',
    transitionStyle: 'Slow fades to absolute black, sudden flash frame distortions, audio jumps.',
    captionStyle: 'Distorted jittery text, blood red highlights, ghosted opacity fades.',
    thumbnailDirection: 'Distorted uncanny face looking through cracked doorway, high-contrast nightmare palette.',
    titleDirection: 'Do NOT Watch This Alone / The Entity Caught On Tape / The Terrifying Truth About',
    shortFormAdjustment: 'Uncanny 3-second hook, eerie buildup over 20s, shock payoff/warning at conclusion.',
    longFormAdjustment: 'Deep atmospheric immersion, world lore, psychological isolation before catastrophic events.',
  },

  'Sci-Fi': {
    id: 'Sci-Fi',
    label: 'Sci-Fi',
    category: 'Genre',
    description: 'Speculative technological horizons, cyberpunk aesthetics, planetary mysteries, and advanced existential dilemmas.',
    narrativeStructure: 'Futurological premise, theoretical technological mechanism, unintended consequence/dystopian divergence, future roadmap.',
    pacing: 'dynamic',
    hookStyle: 'A staggering technological milestone or an eerie prediction from 2050.',
    narrationStyle: 'Visionary, cerebral, polished, articulate, inspiring existential curiosity.',
    visualStyle: 'Holographic HUD overlays, anamorphic blue lens flares, clean chrome surfaces, dark cosmic voids.',
    cameraStyle: 'Smooth robotic gimbal tracks, macroscopic silicon zooms, epic orbital scale reveals.',
    lightingStyle: 'Cyberpunk neon cyan/magenta rim lighting, cold LED strip illumination, deep space specular bounce.',
    musicDirection: 'Vangelis-inspired analog synths, arpeggiated electronic sequences, cosmic ambient pads.',
    soundDirection: 'Futuristic servo hums, data stream telemetry chirps, laser ionization sweeps.',
    sceneDensity: 'medium',
    transitionStyle: 'Digital HUD glitches, holographic swipe reveals, spatial light streaks.',
    captionStyle: 'Cyber neon font, monospaced futuristic telemetry, cyan glowing highlights.',
    thumbnailDirection: 'Glowing cybernetic eye or futuristic megastructure with neon circuit reflections.',
    titleDirection: 'The AI That Changed Humanity / In 2035, This Will Be Mandatory / Scientists Just Created',
    shortFormAdjustment: 'Mind-bending speculative scenario in 2s, 3 holographic rapid proof points, future conclusion.',
    longFormAdjustment: 'Multi-tiered exploration of theoretical science, ethics, and world-scale implications.',
  },

  Space: {
    id: 'Space',
    label: 'Space',
    category: 'Genre',
    description: 'Cosmic scale, astrophysical wonder, interstellar solitude, and deep celestial mysteries.',
    narrativeStructure: 'Mind-boggling astronomical scale comparison, voyage into the unknown, astrophysical barrier, cosmic realization.',
    pacing: 'slow_burn',
    hookStyle: 'A cosmic reality that makes human existence feel infinitesimal.',
    narrationStyle: 'Awe-inspiring, contemplative, resonant, poetic, vast in scope.',
    visualStyle: 'Deep interstellar blacks, photorealistic nebula colors, stellar coronas, orbital horizons.',
    cameraStyle: 'Epic slow drift camera movements, infinite reverse zoom from micro to macro universe.',
    lightingStyle: 'Harsh single-source stellar illumination, pitch dark shadows, soft planetary corona glow.',
    musicDirection: 'Orchestral cosmic majesty (Holst-like), sweeping French horns, ethereal celestial choirs.',
    soundDirection: 'Deep synthetic vacuum rumbles, gravitational waves sonar pings, muffled spacesuit breaths.',
    sceneDensity: 'cinematic_sparse',
    transitionStyle: 'Cosmic scale match cuts, light-speed warp streaks, orbital eclipse fades.',
    captionStyle: 'Minimalist white typography, clean letter-spacing, starlight glow.',
    thumbnailDirection: 'Astronaut floating in infinite void facing a glowing supermassive black hole.',
    titleDirection: 'What NASA Saw At The Edge Of The Universe / The Dark Truth About Deep Space',
    shortFormAdjustment: 'Mind-expanding cosmic size comparison in 3s, breathtaking visuals, vertigo finish.',
    longFormAdjustment: 'Philosophical astrophysical deep dive into physics, relativity, and human destiny.',
  },

  Mystery: {
    id: 'Mystery',
    label: 'Mystery',
    category: 'Narrative',
    description: 'Puzzle-box intrigue, cryptic anomalies, missing persons or artifacts, and breadcrumb clues.',
    narrativeStructure: 'Cryptic riddle or unexplained anomaly hook, layer-by-layer peeling of clues, false leads, shocking revelation.',
    pacing: 'moderate',
    hookStyle: 'An object found where it shouldn\'t be, or a person who vanished in broad daylight.',
    narrationStyle: 'Intriguing, curious, nuanced, whispering an open invitation to solve the puzzle.',
    visualStyle: 'Sepia and antique tones mixed with sharp modern macro photography, locked boxes, coded ciphers.',
    cameraStyle: 'Over-the-shoulder investigative snooping, slow tilt reveals, macro focus pulls on clues.',
    lightingStyle: 'Amber desk lamp pools, foggy streetlamps, shafts of dusty sunlight through blinds.',
    musicDirection: 'Mysterious music box motifs, plucked pizzicato strings, unsettling acoustic guitar.',
    soundDirection: 'Paper rustling, ticking pocket watch, footsteps on gravel, echoing whispers.',
    sceneDensity: 'medium',
    transitionStyle: 'Keyhole wipes, magnifying glass zooms, page-turn transitions.',
    captionStyle: 'Vintage monospaced typewriter style with subtle warm amber highlight.',
    thumbnailDirection: 'Ancient locked diary or silhouette pointing magnifying glass into dark fog.',
    titleDirection: 'The 100-Year-Old Mystery Finally Solved / Nobody Can Explain This / The Hidden Secret Of',
    shortFormAdjustment: 'Introduce 1 cryptic visual anomaly, reveal 2 conflicting clues, challenge viewer to solve.',
    longFormAdjustment: 'Multi-chapter investigative journey examining historical documents and eyewitness testimonies.',
  },

  Investigation: {
    id: 'Investigation',
    label: 'Investigation',
    category: 'Informative',
    description: 'Rigorous forensic journalism, paper trails, whistleblower exposés, and structural truth-seeking.',
    narrativeStructure: 'The public narrative vs hidden reality, following the money/evidence trail, key witness interviews, definitive conclusion.',
    pacing: 'moderate',
    hookStyle: 'A leaked internal memo or financial discrepancy that exposes a massive deception.',
    narrationStyle: 'Sharp, objective, assertive, investigative journalist delivery.',
    visualStyle: 'Document highlighters, digital timeline trees, forensic graphs, split-screen cross-examinations.',
    cameraStyle: 'Corporate glass building reflections, telephoto lens stakeout angle, rapid desk b-roll.',
    lightingStyle: 'Cool neutral white light, high-clarity office illumination, analytical contrast.',
    musicDirection: 'Driving minimalist electronic tick, tension pulse, methodical bass progression.',
    soundDirection: 'Keyboard clatter, camera shutter clicks, telephone ringback tones, file stamp slams.',
    sceneDensity: 'high',
    transitionStyle: 'Red-line document strike-throughs, digital pan across timeline, swift slide cuts.',
    captionStyle: 'Clean bold yellow marker-style highlight on dark rectangular cards.',
    thumbnailDirection: 'Top secret leaked document with red "CONFIDENTIAL" stamp and high-profile target face.',
    titleDirection: 'Exposed: The Billion-Dollar Lie / The Investigation They Tried To Stop / Following The Money',
    shortFormAdjustment: '3 shocking receipts/documents shown in 10s, uncovering the lie with undeniable proof.',
    longFormAdjustment: 'Full journalistic exposé structured across motives, mechanisms, and legal/ethical fallout.',
  },

  Psychological: {
    id: 'Psychological',
    label: 'Psychological',
    category: 'Narrative',
    description: 'Cognitive biases, mental illusions, gaslighting, subconscious drivers, and distorted perception.',
    narrativeStructure: 'Relatable cognitive vulnerability hook, psychological mechanism demonstration, real-world manipulation examples, protective awakening.',
    pacing: 'moderate',
    hookStyle: 'Demonstrating how the viewer\'s own brain is lying to them right now.',
    narrationStyle: 'Intimate, hypnotic, piercingly insightful, psychologically astute.',
    visualStyle: 'Mirrored reflections, kaleidoscopic fractals, optical illusions, soft blurred peripheries.',
    cameraStyle: 'Dolly zooms, extreme close-up on pupil dilation, disorienting 360-degree rotation.',
    lightingStyle: 'Dreamlike ethereal softbox lighting, monochromatic color shifts, split warm/cool facial lighting.',
    musicDirection: 'Subtle ambient binaural beats, reversing reversed piano notes, hypnotic drones.',
    soundDirection: 'Muffled heartbeat, tinnitus frequencies, whispered inner monologue, binaural panning.',
    sceneDensity: 'medium',
    transitionStyle: 'Morph cuts, liquid warp transitions, rack-focus blur dissolutions.',
    captionStyle: 'Minimalist clean typography with fluid opacity breath animations.',
    thumbnailDirection: 'Split human face showing dual contrasting expressions or cracked glass mirror reflection.',
    titleDirection: 'How Your Brain Tricks You Every Day / The Dark Psychology of / Why You Can\'t Stop',
    shortFormAdjustment: 'Instant 2-second interactive brain test, immediate reveal of cognitive bias, viewer takeaway.',
    longFormAdjustment: 'Deep psychological experiment dissection, cognitive science literature, actionable mindset shift.',
  },

  Adventure: {
    id: 'Adventure',
    label: 'Adventure',
    category: 'Lifestyle',
    description: 'Epic journeys, pushing physical frontiers, rugged nature, adrenaline and discovery.',
    narrativeStructure: 'The audacious departure call, uncharted terrain challenge, unexpected hazard, triumphant summit.',
    pacing: 'dynamic',
    hookStyle: 'Standing on the edge of an impossible natural wonder with a high-stakes mission.',
    narrationStyle: 'Passionate, hearty, spirited, rugged and inspirational narrator.',
    visualStyle: 'Golden hour drone sweeps, vibrant saturated greens and blues, dirt/water camera lens splashes.',
    cameraStyle: 'FPV drone dives, action-cam chest mounts, sweeping ultra-wide landscape vistas.',
    lightingStyle: 'Natural golden hour flare, harsh midday desert sun, bonfire night glow.',
    musicDirection: 'Epic uplifting acoustic guitars, swelling brass anthems, galloping acoustic percussion.',
    soundDirection: 'Rushing river rapids, howling mountain wind, boots crunching on gravel, heavy breath.',
    sceneDensity: 'high',
    transitionStyle: 'FPV whip transitions, mountain-ridge masking wipes, rapid dynamic jump cuts.',
    captionStyle: 'Outdoor adventure bold yellow font with rugged border drops.',
    thumbnailDirection: 'Explorer silhouetted atop knife-edge mountain ridge under epic sunrise flare.',
    titleDirection: 'I Walked Across An Entire Desert / Surviving 7 Days In The Wild / The Extreme Expedition',
    shortFormAdjustment: 'Immediate 1s visual stunt hook, rapid 30s survival montage, victorious finish.',
    longFormAdjustment: 'Expansive travelogue mapping logistics, weather setbacks, camaraderie, and ultimate summit.',
  },

  Survival: {
    id: 'Survival',
    label: 'Survival',
    category: 'Narrative',
    description: 'Primal instincts, resource scarcity, life-or-death decision trees, and extreme resilience.',
    narrativeStructure: 'Catastrophic isolation incident, immediate triage & basic needs (water/shelter), crisis challenge, rescue or escape.',
    pacing: 'fast',
    hookStyle: 'You are stranded with 3 hours of daylight and 1 liter of water—what is your first move?',
    narrationStyle: 'Tough, pragmatic, hyper-focused, tactical survivalist voice.',
    visualStyle: 'Bleached sunlight tones, muddy textures, macro fire spark close-ups, thermal heat maps.',
    cameraStyle: 'Ground-level mud-crawling angles, tight survivalist inventory showcases, shaky survival b-roll.',
    lightingStyle: 'Harsh midday sun glare, flickering campfire amber, pitch-black survival darkness.',
    musicDirection: 'Primal wood and bone drums, guttural didgeridoo or low bass pulses, escalating tempo.',
    soundDirection: 'Fire crackling, knife carving wood, shivering breaths, predatory animal growls.',
    sceneDensity: 'high',
    transitionStyle: 'Match cuts on fire sparks, survival timer clock wipe, hard blackout transitions.',
    captionStyle: 'Military stencil bold white text with rugged emergency orange accents.',
    thumbnailDirection: 'Mud-covered hands starting fire with flint in driving rainstorm, survival HUD timer.',
    titleDirection: 'How To Survive 24 Hours Alone In The Arctic / 5 Survival Mistakes That Will Kill You',
    shortFormAdjustment: 'Life-saving survival tip demonstrated in 20 seconds flat with urgent life-or-death hook.',
    longFormAdjustment: 'Full day-by-day survival diary analyzing calories, shelter construction, and psychological grit.',
  },

  Fantasy: {
    id: 'Fantasy',
    label: 'Fantasy',
    category: 'Genre',
    description: 'Mythic lore, enchanted realms, legendary artifacts, magic systems, and epic hero destinies.',
    narrativeStructure: 'Ancient prophecy or relic discovery, magical world exploration, dark corrupting force, legendary clash.',
    pacing: 'moderate',
    hookStyle: 'An ancient scroll that foretells an impossible magical event.',
    narrationStyle: 'Grand, mystical, storyteller cadence, rich with theatrical gravitas.',
    visualStyle: 'Glowing ethereal runes, magical bioluminescence, misty enchanted forests, medieval stone castle aesthetic.',
    cameraStyle: 'Slow mythological crane shots, spinning magical orbital moves, sweeping landscape flyovers.',
    lightingStyle: 'Soft magical fairy glow, deep mystical purple and emerald bioluminescence, torchlight.',
    musicDirection: 'Lush orchestral fantasy suites, Celtic harps, soaring female vocalise, epic horns.',
    soundDirection: 'Magical spell whooshes, chime sparkles, clashing swords, distant dragon roars.',
    sceneDensity: 'medium',
    transitionStyle: 'Magical particle dissipations, parchment smoke transitions, glowing light wipes.',
    captionStyle: 'Gothic serif typography, gold-leaf letter styling, shimmering ambient glow.',
    thumbnailDirection: 'Glowing mythical weapon embedded in glowing runes with towering dragon silhouette.',
    titleDirection: 'The Forgotten Lore Of / The Legendary Realm Nobody Knows / Secret Magic of',
    shortFormAdjustment: 'Drop into magical visual hook immediately, explain 1 jaw-dropping lore rule in 30s.',
    longFormAdjustment: 'Expansive worldbuilding acts covering factions, ancient battles, and magical lineages.',
  },

  Romance: {
    id: 'Romance',
    label: 'Romance',
    category: 'Narrative',
    description: 'Intimate emotional resonance, romantic tension, vulnerable chemistry, and heartfelt journeys.',
    narrativeStructure: 'The fateful encounter, burgeoning vulnerability, the heartbreaking obstacle/misunderstanding, heartfelt reconciliation.',
    pacing: 'slow_burn',
    hookStyle: 'A vulnerable romantic confession or an unforgettable fateful glance across a crowded room.',
    narrationStyle: 'Warm, soft, empathetic, emotionally honest, heartfelt narrator.',
    visualStyle: 'Soft focus bokeh, warm pastel tones, golden hour lens flares, gentle film grain.',
    cameraStyle: 'Intimate close-ups on eyes and intertwined fingers, slow gentle tracking moves.',
    lightingStyle: 'Warm sunset glow, fairy string lights, candlelit ambiance, soft diffused daylight.',
    musicDirection: 'Acoustic fingerstyle guitar, melancholic romantic piano, gentle orchestral swells.',
    soundDirection: 'Soft laughter, rain on cafe window, gentle sighs, fabric rustles, warm coffee pour.',
    sceneDensity: 'cinematic_sparse',
    transitionStyle: 'Soft cross-dissolves, light flare washes, gentle blurs.',
    captionStyle: 'Elegant cursive-accented modern serif typography with soft blush pink glow.',
    thumbnailDirection: 'Warm golden hour silhouette of two figures almost touching hands, emotional typography.',
    titleDirection: 'The Love Story That Defied All Odds / Why True Chemistry Feels Like This',
    shortFormAdjustment: 'High-emotion relatable romantic dialogue or dilemma, 30s heartfelt arc, touching ending.',
    longFormAdjustment: 'Deep character psychological emotional arcs, relationship milestones, and vulnerable storytelling.',
  },

  Comedy: {
    id: 'Comedy',
    label: 'Comedy',
    category: 'Lifestyle',
    description: 'Irreverent humor, sharp comedic timing, subverted expectations, self-deprecation, and absurd sketches.',
    narrativeStructure: 'Relatable everyday premise, absurd escalation, the awkward peak catastrophe, punchline button.',
    pacing: 'rapid',
    hookStyle: 'A hilarious relatable blunder or a completely unhinged contrarian statement.',
    narrationStyle: 'High-energy, sarcastic, playful, self-deprecating, razor-sharp comic timing.',
    visualStyle: 'Bright saturated colors, funny freeze-frames with text callouts, cartoonish pop stickers.',
    cameraStyle: 'The Office-style zoom ins on deadpan reactions, whip pans, sudden wide reveal shots.',
    lightingStyle: 'High-key bright commercial lighting, crisp clean colors, no dark shadows.',
    musicDirection: 'Upbeat funky basslines, quirky pizzicato bass, comedic kazoo or brass stabs.',
    soundDirection: 'Record scratches, cartoon boings, funny squishy foley, vine thuds, meme audio cues.',
    sceneDensity: 'high',
    transitionStyle: 'Snap zooms, goofy slide wipes, sudden cut to black on awkward pause.',
    captionStyle: 'Bold playful yellow and white pop font, animated bounce words, emoji accents.',
    thumbnailDirection: 'Extreme exaggerated face reaction, hilarious juxtaposition, bold meme-style question.',
    titleDirection: 'I Regret Everything / Why Nobody Should Ever Do This / The Dumbest Experiment in History',
    shortFormAdjustment: 'Setup in 2s, punchy escalation, subversion punchline at second 25, meme sound finish.',
    longFormAdjustment: 'Series of comedic escalations, running gags, comedic sketches, and grand finale disaster.',
  },

  Drama: {
    id: 'Drama',
    label: 'Drama',
    category: 'Narrative',
    description: 'Human conflict, moral dilemmas, character transformations, deep emotional stakes, and poignant truths.',
    narrativeStructure: 'The simmering moral conflict hook, character crisis point, confrontation, bittersweet resolution.',
    pacing: 'slow_burn',
    hookStyle: 'A gut-wrenching life choice where every option costs everything.',
    narrationStyle: 'Somber, deeply empathetic, measured, poignant, emotionally grounded.',
    visualStyle: 'Rich cinematic shadows, desaturated cool tones, authentic natural textures, deep character focus.',
    cameraStyle: 'Lingering medium close-ups holding through emotional silence, deliberate steady tracking.',
    lightingStyle: 'Moody window side-light (Rembrandt lighting), muted overcast daylight, dramatic contrast.',
    musicDirection: 'Solo cello compositions, emotive piano progressions, restrained string quartet swells.',
    soundDirection: 'Subtle ambient silence, ticking clock, emotional vocal catches, heavy rain exterior.',
    sceneDensity: 'cinematic_sparse',
    transitionStyle: 'L-cuts holding on character reaction faces, cinematic black fades, slow dissolves.',
    captionStyle: 'Sophisticated modern serif, subtle cream tone on charcoal backing.',
    thumbnailDirection: 'Intense cinematic portrait with single tear or resolute gaze in dramatic side-lighting.',
    titleDirection: 'The Day Everything Changed / The Hardest Decision Anyone Can Make / A True Human Story',
    shortFormAdjustment: 'High-intensity emotional dilemma hook, 30s moral crisis, resonant closing life lesson.',
    longFormAdjustment: 'Deep multi-perspective narrative exploring interpersonal stakes and lasting transformation.',
  },

  Historical: {
    id: 'Historical',
    label: 'Historical',
    category: 'Informative',
    description: 'Epic eras, forgotten civilizational turning points, period accuracy, and archival resonance.',
    narrativeStructure: 'Vivid period immersion hook, societal crisis/battle context, key historical figures, enduring legacy.',
    pacing: 'moderate',
    hookStyle: 'Transporting the viewer to a specific date in history moments before world-changing chaos.',
    narrationStyle: 'Epic, regal, articulate, timeless storytelling historian cadence.',
    visualStyle: 'Aged parchment textures, historical oil painting zooms, animated vintage map routes, film dust.',
    cameraStyle: 'Ken Burns style smooth pan-and-zooms on archival paintings and maps, grand architectural sweeps.',
    lightingStyle: 'Candlelight and hearth fire illumination, historic lantern glow, dusty museum shafts of light.',
    musicDirection: 'Period-accurate acoustic instruments, epic historical brass marches, choral chants.',
    soundDirection: 'Horse hooves on cobblestones, quill pen scribbling, distant cannon fire, marching boots.',
    sceneDensity: 'medium',
    transitionStyle: 'Ink-bleed transitions, parchment burn wipes, map boundary expansion reveals.',
    captionStyle: 'Classic historic serif font, gold antique trim, elegant historic quotes.',
    thumbnailDirection: 'Historical figure portrait layered over flaming vintage battle map with bold bold question.',
    titleDirection: 'The 24 Hours That Changed Human History / The Forgotten Empire That Ruled The World',
    shortFormAdjustment: 'Immediate "On this exact day in 1842..." hook, rapid animated map, legacy mind-blow.',
    longFormAdjustment: 'Exhaustive chronological campaign breakdown with battle tactics, diplomacy, and societal shifts.',
  },

  Biography: {
    id: 'Biography',
    label: 'Biography',
    category: 'Narrative',
    description: 'Intimate human journeys of extraordinary leaders, innovators, underdogs, and iconoclasts.',
    narrativeStructure: 'The humble obscure origin, the defining obsessive breakthrough, the catastrophic failure, lasting legacy.',
    pacing: 'moderate',
    hookStyle: 'Before they were worth billions, this person was sleeping in a broken car with $7 in their pocket.',
    narrationStyle: 'Inspiring, intimate, analytical, celebratory yet candid about flaws.',
    visualStyle: 'Chronological photo timelines, animated quote cards, nostalgic 35mm film memories, modern achievement b-roll.',
    cameraStyle: 'Portrait close-up framing, slow dramatic push-ins on pivotal turning point photographs.',
    lightingStyle: 'Studio portrait softbox, warm nostalgic sepia for childhood, crisp modern light for success.',
    musicDirection: 'Underdog building anthems, piano arpeggios that evolve into triumphant orchestral builds.',
    soundDirection: 'Camera clicks, audio soundbites from real speeches, typing keys, stadium applause.',
    sceneDensity: 'medium',
    transitionStyle: 'Timeline year flip transitions, photo album wipes, flashbulbs.',
    captionStyle: 'Crisp editorial sans-serif, clean monochrome styling, quoted words emphasized in gold.',
    thumbnailDirection: 'Side-by-side young obscure photo vs legendary modern icon portrait with transformative arrow.',
    titleDirection: 'How One Rejected Kid Built An Empire / The Untold Struggle Of / The Mind Behind',
    shortFormAdjustment: '30-second zero-to-hero underdog trajectory with 3 rapid turning points and golden advice.',
    longFormAdjustment: 'Three-act biographical structure detailing childhood psychology, key gambles, and philosophies.',
  },

  News: {
    id: 'News',
    label: 'News',
    category: 'Informative',
    description: 'Urgent journalistic breaking developments, geopolitical stakes, real-time facts, and immediate analysis.',
    narrativeStructure: 'Breaking headline fact hook, who/what/when/where summary, verified implications, developing outlook.',
    pacing: 'rapid',
    hookStyle: 'Breaking updates right now: Here is what just happened and why you need to know immediately.',
    narrationStyle: 'Fast, clear, objective, urgent, professional news broadcast delivery.',
    visualStyle: 'Lower-third ticker banners, satellite maps, newsroom studio backdrops, verified badge graphics.',
    cameraStyle: 'Direct-to-lens locked anchor framing, dynamic graphic pop push-ins, live feed split screens.',
    lightingStyle: 'Bright 5600K balanced daylight newsroom studio lighting, high contrast graphics.',
    musicDirection: 'Urgent rhythmic electronic ticker beats, low news stingers, pulsing synth updates.',
    soundDirection: 'News stinger whooshes, breaking alert pings, camera flashes, live room tone.',
    sceneDensity: 'high',
    transitionStyle: 'News ticker sweeps, digital split wipes, graphic banner zooms.',
    captionStyle: 'High-visibility white text on solid black or red news banner blocks.',
    thumbnailDirection: 'High-contrast headline visual, red "BREAKING" alert banner, urgent map or subject cutout.',
    titleDirection: 'BREAKING: What Just Happened / Urgent Announcement: What You Need To Know Today',
    shortFormAdjustment: 'Deliver the core verified facts in the first 5 seconds, explain impact in next 25s, sign-off.',
    longFormAdjustment: 'Comprehensive multi-source analysis, geopolitical/economic context, expert commentary compilation.',
  },

  Explainer: {
    id: 'Explainer',
    label: 'Explainer',
    category: 'Informative',
    description: 'Deconstructing complex concepts into intuitive mental models, animated graphics, and eureka moments.',
    narrativeStructure: 'The counterintuitive puzzle hook, simplifying the complex engine/system, concrete visual analogy, practical takeaway.',
    pacing: 'moderate',
    hookStyle: 'You interact with this system every single day, but almost nobody understands how it actually works.',
    narrationStyle: 'Clear, charismatic, articulate, conversational, master-teacher tone.',
    visualStyle: 'Minimalist 2D motion graphics, 3D exploded diagrams, clear color-coded flowcharts, sleek UI simulations.',
    cameraStyle: 'Isometric graphic perspectives, screen recordings with smooth camera zooms, center-framed analogies.',
    lightingStyle: 'Clean studio softbox key light, aesthetic pastel accents, minimalist background illumination.',
    musicDirection: 'Upbeat Lo-Fi study beats, cheerful modern tech synth plucks, curious marimba taps.',
    soundDirection: 'Pop sounds, UI clicks, smooth whooshes, digital bell eureka dings.',
    sceneDensity: 'high',
    transitionStyle: 'Smooth kinetic zoom-throughs, vector shape morphs, seamless pan wipes.',
    captionStyle: 'Karaoke glow or clean pop bold with dynamic keyword highlight boxes.',
    thumbnailDirection: 'Exploded 3D diagram or side-by-side simple analogy with bright clean background.',
    titleDirection: 'How This Actually Works / The Simple Math Behind / Why Everything You Know About X Is Wrong',
    shortFormAdjustment: 'Punchy visual analogy in 3s, step 1-2-3 breakdown in 30s, eureka takeaway in last 5s.',
    longFormAdjustment: 'Multi-chapter deep breakdown with case studies, counter-examples, and technical blueprints.',
  },

  Educational: {
    id: 'Educational',
    label: 'Educational',
    category: 'Informative',
    description: 'Structured pedagogical teaching, foundational principles, real-world examples, and actionable mastery.',
    narrativeStructure: 'Core concept definition hook, structured framework points (Rule 1, Rule 2, Rule 3), common pitfalls, mastery application.',
    pacing: 'moderate',
    hookStyle: 'The 1 foundational rule that transforms your understanding of this subject forever.',
    narrationStyle: 'Patient, structured, articulate, authoritative yet warm and encouraging.',
    visualStyle: 'Clean whiteboard diagrams, step-by-step bullet lists, high-contrast mathematical graphs.',
    cameraStyle: 'Instructor eye-level medium shot, PIP screen shares, smooth digital whiteboard zooms.',
    lightingStyle: 'Even studio lighting, soft key fill, professional academic background ambiance.',
    musicDirection: 'Focus ambient electronic music, gentle acoustic guitar study music, calming rhythmic pulses.',
    soundDirection: 'Chalk or marker strokes, page turns, subtle affirmative chimes, crisp vocal clarity.',
    sceneDensity: 'medium',
    transitionStyle: 'Simple clean slide cuts, numerical chapter banners, fade to slide transitions.',
    captionStyle: 'Classic sub clean high-contrast text with emphasized rule definitions.',
    thumbnailDirection: 'Clear chalkboard or graphic checklist with green checkmarks and bold question.',
    titleDirection: 'Complete Masterclass: / The Only Guide You Need To Master / Learn In 15 Minutes',
    shortFormAdjustment: '1 crucial lesson taught in under 45 seconds with 1 clear diagram and 1 actionable rule.',
    longFormAdjustment: 'Curriculum-style progression from fundamentals to advanced edge cases and exercises.',
  },

  Travel: {
    id: 'Travel',
    label: 'Travel',
    category: 'Lifestyle',
    description: 'Cultural discovery, breathtaking landscapes, sensory cuisine, local hidden gems, and wanderlust blueprints.',
    narrativeStructure: 'Arrival sensory shock hook, navigating the bustling local neighborhood, secret local insider spot, reflective wanderlust summary.',
    pacing: 'dynamic',
    hookStyle: 'Stepping off the train into a hidden alleyway that doesn\'t exist on standard Google Maps.',
    narrationStyle: 'Vibrant, warm, curious, evocative, experiential and welcoming adventurer.',
    visualStyle: 'Saturated natural colors, golden hour sunlight, street food sizzling macro shots, cultural architecture b-roll.',
    cameraStyle: 'Walking point-of-view gimbal shots, smooth 360 degree pan reveals, mouthwatering food close-ups.',
    lightingStyle: 'Warm natural sun, glowing street lanterns, neon night market stalls.',
    musicDirection: 'Local traditional acoustic fusion, upbeat tropical/chill acoustic guitar, joyful travel beats.',
    soundDirection: 'Sizzling woks, distant temple bells, bustling market banter, ocean waves crashing.',
    sceneDensity: 'high',
    transitionStyle: 'Whip pans through street corners, blur-ins, dynamic walking match cuts.',
    captionStyle: 'Friendly bold pop text with country flag emoji and location pin highlights.',
    thumbnailDirection: 'Creator tasting incredible street food against stunning ancient temple backdrop.',
    titleDirection: 'I Found The Secret City In / 48 Hours In The World\'s Most Beautiful Place / Ultimate Guide To',
    shortFormAdjustment: 'Show top 3 secret spots in 30 seconds with instant pricing and location tags.',
    longFormAdjustment: 'Full day-to-day itinerary including transportation, cultural etiquette, costs, and hidden gems.',
  },

  Gaming: {
    id: 'Gaming',
    label: 'Gaming',
    category: 'Lifestyle',
    description: 'High-energy gameplay highlights, clutch esports moments, meta analyses, and gaming culture.',
    narrativeStructure: 'Insane challenge or impossible match intro hook, strategy breakdown, clutch battle execution, final score/victory.',
    pacing: 'rapid',
    hookStyle: 'They said this boss was literally mathematically impossible to defeat without cheats.',
    narrationStyle: 'Hyper-energetic, hyped, passionate, gamer vernacular and humorous commentary.',
    visualStyle: 'Direct 4K 60fps gameplay capture, facecam reaction overlay, colorful HUD graphics, meme popups.',
    cameraStyle: 'Facecam with dynamic punch-ins on intense moments, smooth in-game cinematic replay angles.',
    lightingStyle: 'RGB gamer studio neon (purple/cyan LED light bars), dynamic reactive lighting.',
    musicDirection: 'Driving chiptune electronic trap, intense boss battle orchestral rock, energetic synthwave.',
    soundDirection: 'Hit markers, level-up fanfares, 8-bit coin pings, keyboard mechanical clicks, victory horns.',
    sceneDensity: 'high',
    transitionStyle: 'Pixelated glitch transitions, speed ramps on killcams, rapid screen shake impacts.',
    captionStyle: 'Cyber neon bold pop font, vibrating text on loud shouts, game damage number popups.',
    thumbnailDirection: 'Shocked gamer facecam next to terrifying game boss with glowing red HP bar at 1%.',
    titleDirection: 'I Beat The Hardest Game in 24 Hours / The Secret Strat That Broke The Meta',
    shortFormAdjustment: '5-second setup of impossible play, 20-second clutch execution, screaming victory celebration.',
    longFormAdjustment: 'Full tournament or playthrough chronicle with tactical meta breakdowns and comedic fails.',
  },

  Technology: {
    id: 'Technology',
    label: 'Technology',
    category: 'Informative',
    description: 'Cutting-edge gadget hardware, software breakthroughs, silicon engineering, and the future of consumer tech.',
    narrativeStructure: 'The flagship device unboxing or breakthrough specs hook, stress test benchmarks, real-world day-in-the-life testing, final verdict.',
    pacing: 'fast',
    hookStyle: 'This new piece of hardware makes everything you currently own look like ancient technology.',
    narrationStyle: 'Sleek, polished, knowledgeable, tech-enthusiast, honest consumer advocate.',
    visualStyle: 'Clean minimal studio desk setup, macro probe lens shots on silicon chips, matte black textures.',
    cameraStyle: 'Motorized slider tracks, silky smooth macro pan shots on gadget edges, top-down flat-lay framing.',
    lightingStyle: 'Soft diffused high-CRI studio softboxes, subtle rim lighting highlighting sleek matte edges.',
    musicDirection: 'Modern lo-fi tech beats, ambient minimalist electronic pulses, modern clean future bass.',
    soundDirection: 'Unboxing tape peeling, mechanical switch clicks, sleek digital UI whooshes.',
    sceneDensity: 'high',
    transitionStyle: 'Clean wipe transitions, smooth product rotation match cuts, slider pans.',
    captionStyle: 'Minimalist tech typography, glowing white on dark matte background.',
    thumbnailDirection: 'Pristine macro shot of mysterious new gadget with glowing screen and bold "GAME OVER?" text.',
    titleDirection: 'The New Device That Changes Everything / I Replaced My Entire Setup With This / Don\'t Buy Until You See This',
    shortFormAdjustment: 'Feature highlight in 3 seconds, real-world test in 15 seconds, worth it or skip verdict in 5s.',
    longFormAdjustment: 'In-depth benchmark tests, battery endurance trials, software bugs, and competitive comparisons.',
  },

  Sports: {
    id: 'Sports',
    label: 'Sports',
    category: 'Lifestyle',
    description: 'Athletic prowess, legendary rivalries, comeback triumphs, tactical playbooks, and peak human performance.',
    narrativeStructure: 'Championship buzzer-beater stakes hook, tactical challenge, athletic training grind, unforgettable victory.',
    pacing: 'rapid',
    hookStyle: 'Down 10 points with 42 seconds left on the clock: the greatest comeback in history.',
    narrationStyle: 'High-octane color commentator energy, passionate, dramatic cadence, electric delivery.',
    visualStyle: 'Ultra high-speed 1000fps slow-mo sweat droplets, stadium floodlights, dynamic tactical play diagrams.',
    cameraStyle: 'Sideline tracking cameras, drone stadium sweeps, tight telephoto focus on athlete eyes.',
    lightingStyle: 'Stadium floodlights, dramatic high-contrast sports photography rim lights.',
    musicDirection: 'Swelling stadium rock anthems, driving battle drums, emotional orchestral sports crescendos.',
    soundDirection: 'Sneakers squeaking on hardwood, crowd roar crescendo, whistle blow, ball swish.',
    sceneDensity: 'high',
    transitionStyle: 'Whip cuts, flashbulb strobes, rapid replay speed ramps.',
    captionStyle: 'Bold athletic varsity font, bright yellow and white pop.',
    thumbnailDirection: 'Iconic screaming athletic celebration snapshot with stadium confetti and score graphic.',
    titleDirection: 'The Most Disrespected Player Who Proved Everyone Wrong / The Play That Shocked The World',
    shortFormAdjustment: 'Buzzer-beater highlight in 2s, slow-mo replay from 3 angles, crowd eruption finale.',
    longFormAdjustment: 'Full historical breakdown of rivalry tactics, locker-room interviews, and career trajectories.',
  },

  'War History': {
    id: 'War History',
    label: 'War History',
    category: 'Informative',
    description: 'Tactical battle campaigns, military strategy maps, heroic sacrifice, and monumental military turning points.',
    narrativeStructure: 'The strategic battlefield dilemma hook, opposing forces & geography breakdown, the fatal maneuver, aftermath and historical shift.',
    pacing: 'moderate',
    hookStyle: 'One single miscalculated order caused the annihilation of an entire army in under 3 hours.',
    narrationStyle: 'Grave, authoritative, deeply respectful, tactical military historian delivery.',
    visualStyle: 'Detailed top-down tactical troop movement maps, archival battle photographs, smoke and ash textures.',
    cameraStyle: 'Tactical camera sweeps across 3D terrain maps, slow zooms into battlefield coordinates.',
    lightingStyle: 'Overcast combat sky, fiery explosions in twilight, muted desaturated war documentary palette.',
    musicDirection: 'Heavy military snare cadence, mournful war cellos, grand somber brass fanfares.',
    soundDirection: 'Artillery rumbles, trench sirens, marching boots in mud, radio chatter static.',
    sceneDensity: 'medium',
    transitionStyle: 'Tactical map arrow animations, smoke dissolves, vintage film burn cuts.',
    captionStyle: 'Stark stencil or monospaced military typography with tactical coordinates.',
    thumbnailDirection: '3D tactical map showing red vs blue arrows collapsing surrounded by smoke and battle art.',
    titleDirection: 'The Blunder That Ended The War / The Forgotten Battle That Decided World War II',
    shortFormAdjustment: 'Explain 1 genius tactical military maneuver on animated map in 40 seconds flat.',
    longFormAdjustment: 'Full tactical breakdown including supply chains, troop divisions, command psychology, and casualties.',
  },

  'Post-Apocalyptic': {
    id: 'Post-Apocalyptic',
    label: 'Post-Apocalyptic',
    category: 'Genre',
    description: 'Ruined civilizations, wasteland survival, scavenged machinery, and solitary resilience after the collapse.',
    narrativeStructure: 'The silent ruined landscape hook, daily survival protocol in the wasteland, unexpected human contact or hazard, finding hope.',
    pacing: 'slow_burn',
    hookStyle: 'The world ended 40 years ago. Today, the emergency radio broadcast finally responded.',
    narrationStyle: 'Gravelly, weary, haunted yet resilient, gritty survivor narration.',
    visualStyle: 'Rusted metal textures, overgrown city foliage, ash falling like snow, dust storms, gas mask HUDs.',
    cameraStyle: 'Desolate wide static shots of abandoned skyscrapers, slow tracking through hollow ruins.',
    lightingStyle: 'Dusty amber nuclear twilight, cold desolate ash skies, flickering campfire embers.',
    musicDirection: 'Distorted industrial acoustic guitars, hollow wind drones, scraping metallic ambient pieces.',
    soundDirection: 'Geiger counter clicks, wind whistling through broken glass, distant anomalous thuds.',
    sceneDensity: 'cinematic_sparse',
    transitionStyle: 'Static interference glitches, slow ash fades, desolate hard cuts.',
    captionStyle: 'Distressed grunge stencil typography, radioactive hazard yellow highlights.',
    thumbnailDirection: 'Loner wearing gas mask standing atop overgrown rusted freeway overpass looking at ruin.',
    titleDirection: 'What Life Actually Looks Like 50 Years After The Fall / Surviving The Wasteland',
    shortFormAdjustment: 'Immerse viewer in eerie post-apocalyptic scene in 2s, scavenge reveal, ominous conclusion.',
    longFormAdjustment: 'Detailed world lore of how the collapse occurred, wasteland economics, factions, and hope.',
  },

  Superhero: {
    id: 'Superhero',
    label: 'Superhero',
    category: 'Genre',
    description: 'Mythic powers, moral responsibility, towering villains, epic city-level showdowns, and heroic sacrifice.',
    narrativeStructure: 'Catastrophic villain emergence hook, the hero\'s inner struggle/vulnerability, the grand city clash, triumphant sacrifice.',
    pacing: 'fast',
    hookStyle: 'A threat emerged that no conventional military force on Earth could even scratch.',
    narrationStyle: 'Epic, courageous, inspiring, resonant, mythic hero storyteller.',
    visualStyle: 'Vibrant comic-book primary colors, cinematic lightning, crumbling concrete, heroic silhouettes.',
    cameraStyle: 'Dynamic Dutch angles, heroic low-angle tilt-ups, high-speed flying point-of-view shots.',
    lightingStyle: 'Heroic golden rim lighting, blinding energy beam specular highlights, dark villainous shadows.',
    musicDirection: 'Massive superhero orchestral themes with booming brass, choir, and heroic trumpet fanfares.',
    soundDirection: 'Super-sonic boom whooshes, concrete cracking, laser hums, energy shield impacts.',
    sceneDensity: 'high',
    transitionStyle: 'Comic book panel wipes, sonic boom motion blur transitions, lightning strikes.',
    captionStyle: 'Bold punchy comic pop font with dynamic drop shadows and superhero glow.',
    thumbnailDirection: 'Hero floating mid-air charging glowing energy fists facing towering apocalyptic villain.',
    titleDirection: 'The Most Overpowered Character In Fiction / The Hero Who Had To Sacrifice Everything',
    shortFormAdjustment: 'Instant power comparison in 2s, 3 god-tier feat showcases, epic concluding question.',
    longFormAdjustment: 'Deep lore breakdown comparing comic origin variations, philosophical morality, and power limits.',
  },

  'Cinematic Story': {
    id: 'Cinematic Story',
    label: 'Cinematic Story',
    category: 'Narrative',
    description: 'Hollywood visual storytelling, widescreen 2.39:1 immersion, deep character arcs, and cinematic grandeur.',
    narrativeStructure: 'Striking poetic opening image hook, classic three-act narrative arch, emotional midpoint reversal, cathartic climax.',
    pacing: 'dynamic',
    hookStyle: 'A haunting visual tableau accompanied by a single sentence that recontextualizes everything.',
    narrationStyle: 'Rich, cinematic voiceover, nuanced pacing, poetic rhythm and theatrical precision.',
    visualStyle: 'Widescreen letterboxing, 35mm film grain, cinematic color grade (warm shadows, soft teal highlights), volumetric light rays.',
    cameraStyle: 'Smooth Chapman crane movements, Steadicam master tracking shots, shallow depth-of-field close-ups.',
    lightingStyle: 'Painterly three-point cinematic lighting with motivated practical lamps and soft atmospheric haze.',
    musicDirection: 'Hans Zimmer-inspired swelling hybrid orchestral themes, gentle character motifs, evocative cello.',
    soundDirection: 'Pristine spatial audio soundscape, delicate atmospheric foley, massive dynamic range from silence to thunder.',
    sceneDensity: 'medium',
    transitionStyle: 'Cinematic match dissolves, thematic cutaways, elegant widescreen fades.',
    captionStyle: 'Refined cinematic subtitles, centered white typography with subtle drop shadow.',
    thumbnailDirection: 'Widescreen cinematic still showing subject in evocative landscape with letterbox bars.',
    titleDirection: 'The Untold Story / A Cinematic Odyssey / The Journey of a Lifetime',
    shortFormAdjustment: 'Widescreen cinematic opening hook in 2s, rapid emotional arc, breathtaking visual finish.',
    longFormAdjustment: 'Rich multi-act cinematic film experience with dedicated prologue, character themes, and epilogue.',
  },

  'Drama Thriller': {
    id: 'Drama Thriller',
    label: 'Drama Thriller',
    category: 'Narrative',
    description: 'High-tension interpersonal conflict, corporate corruption, family secrets, and relentless psychological suspense.',
    narrativeStructure: 'A hidden betrayal exposed hook, escalating blackmail or stakes, desperate gambit, devastating confrontation.',
    pacing: 'fast',
    hookStyle: 'A secret conversation recorded behind closed doors that threatens to destroy everything.',
    narrationStyle: 'Sharp, urgent, cynical, intense, driving the viewer through high-stakes human deception.',
    visualStyle: 'Cool steel blue palette, glass boardroom reflections, rainy city streets, sharp architectural lines.',
    cameraStyle: 'Tight over-the-shoulder perspectives, slow ominous push-ins on tense conversations, handheld tremors.',
    lightingStyle: 'High-contrast moody executive lighting, streetlights reflecting on wet pavement.',
    musicDirection: 'Tense ticking electronic bass pulses, discordant piano keys, sudden string shrieks.',
    soundDirection: 'Phone vibrating on wood, heavy footsteps outside door, muffled arguments, paper shredder.',
    sceneDensity: 'high',
    transitionStyle: 'Smash cuts on door slams, rapid jump cuts, blackouts.',
    captionStyle: 'Stark white uppercase text on deep black background.',
    thumbnailDirection: 'Whispering silhouettes behind frosted glass door with glowing smartphone screen.',
    titleDirection: 'The Betrayal That Ended A Dynasty / Caught On Tape: The Deal Nobody Was Supposed To Hear',
    shortFormAdjustment: 'Drop into intense argument/secret immediately, 25 seconds of escalating danger, shocking cliffhanger.',
    longFormAdjustment: 'Complex web of motives, financial records, shifting alliances, and irreversible consequences.',
  },

  Custom: {
    id: 'Custom',
    label: 'Custom Mode',
    category: 'Genre',
    description: 'Fully flexible, creator-directed storytelling format tailored to bespoke creator styles and hybrid genres.',
    narrativeStructure: 'Custom dynamic narrative flow aligned with user instructions, balancing engagement hooks with targeted takeaways.',
    pacing: 'dynamic',
    hookStyle: 'Custom bespoke hook designed specifically for creator tone and audience expectations.',
    narrationStyle: 'Adaptable creator brand voice tailored to requested tone and guidelines.',
    visualStyle: 'Creator-defined visual grammar blending requested aesthetics.',
    cameraStyle: 'Adaptive camera grammar matching pacing and platform format.',
    lightingStyle: 'Custom atmospheric lighting suited to narrative goals.',
    musicDirection: 'Bespoke music cues matching mood, genre, and tempo.',
    soundDirection: 'Targeted foley and audio design reinforcing core message.',
    sceneDensity: 'medium',
    transitionStyle: 'Custom style transitions suited to platform format.',
    captionStyle: 'Configurable caption styling tailored to brand guidelines.',
    thumbnailDirection: 'Creator-branded thumbnail concept maximizing audience click-through rate.',
    titleDirection: 'Creator-tailored engaging title formulation.',
    shortFormAdjustment: 'Optimized for vertical short-form retention with immediate 3-second hook.',
    longFormAdjustment: 'Structured for multi-chapter horizontal watch time and viewer satisfaction.',
  },
};

export const ALL_STORY_MODES: StoryMode[] = Object.keys(STORY_MODE_PROFILES) as StoryMode[];
