import { Project, StoryModeOption } from '../types';

export const STORY_MODES: StoryModeOption[] = [
  {
    id: 'sci-fi',
    name: 'Sci-Fi',
    category: 'Genre',
    description: 'Speculative cosmic mechanics, advanced Dyson architectures, relativistic time dilation.',
    atmosphere: 'Cold vacuum, neon luminescence, mathematical precision',
    pacing: 'Thoughtful build-up with sudden cosmic revelations',
    targetTone: 'Awe, intellectual dread, wonder',
    tags: ['Cosmic', 'Tech', 'Astrophysics', 'Synthetic Intellect'],
  },
  {
    id: 'space',
    name: 'Deep Space',
    category: 'Genre',
    description: 'Isolation in the interstellar abyss, deep voyager telemetry, silent orbits.',
    atmosphere: 'Silent stellar voids, low rumble of fusion drives, telemetry pinging',
    pacing: 'Methodical, atmospheric, claustrophobic',
    targetTone: 'Sublime insignificance, quiet endurance',
    tags: ['Orbital', 'Voyage', 'Telemetry', 'Abyss'],
  },
  {
    id: 'mystery',
    name: 'Mystery',
    category: 'Narrative',
    description: 'Cryptic signals, missing crews, paradoxical sensor readings and puzzle-boxes.',
    atmosphere: 'Shadowed corridors, flickering holograms, encrypted manifests',
    pacing: 'Intricately layered investigative reveals',
    targetTone: 'Suspense, paranoia, relentless curiosity',
    tags: ['Investigation', 'Redactions', 'Cipher', 'Anomaly'],
  },
  {
    id: 'documentary',
    name: 'Documentary',
    category: 'Informational',
    description: 'Objective archival synthesis, expert testimonies, observational expedition logs.',
    atmosphere: 'Clean HUD overlays, spectral data charts, historical logs',
    pacing: 'Authoritative, analytical, rhythmic chapters',
    targetTone: 'Grounded truth, grand historical scope',
    tags: ['Archival', 'Data-Driven', 'Expedition', 'Analysis'],
  },
  {
    id: 'thriller',
    name: 'Thriller',
    category: 'Narrative',
    description: 'Ticking oxygen clocks, containment breaches, high-stakes orbital intercept.',
    atmosphere: 'Strobe emergency lights, escalating biometric alerts, rapid telemetry',
    pacing: 'High octane, relentless forward momentum',
    targetTone: 'Visceral adrenaline, immediate peril',
    tags: ['Peril', 'Countdown', 'Escape', 'Breach'],
  },
  {
    id: 'psychological',
    name: 'Psychological',
    category: 'Cinematic',
    description: 'Sensory degradation in hypersleep, unreliable cockpit AI, phantom echoes.',
    atmosphere: 'Dreamlike audio distortion, mirror distortions, temporal confusion',
    pacing: 'Hypnotic, destabilizing, psychological spiral',
    targetTone: 'Existential vertigo, uncanny dread',
    tags: ['Mind', 'Hallucination', 'Isolation', 'Ego Death'],
  },
  {
    id: 'investigation',
    name: 'Investigation',
    category: 'Narrative',
    description: 'Forensic telemetry reconstruction, black box decoding, corporate espionage.',
    atmosphere: 'Fluorescent lab terminals, audio spectrographs, classified files',
    pacing: 'Deductive, methodical, compounding clues',
    targetTone: 'Clinical scrutiny, uncovering corruption',
    tags: ['Forensics', 'Black Box', 'Evidence', 'Audit'],
  },
  {
    id: 'horror',
    name: 'Cosmic Horror',
    category: 'Genre',
    description: 'Non-Euclidean spatial anomalies, ancient dormant leviathans beyond the rim.',
    atmosphere: 'Stifling darkness, unnatural geometric shadows, deep infrasound',
    pacing: 'Creeping revelation leading to overwhelming terror',
    targetTone: 'Helpless dread, sanity breakdown',
    tags: ['Void', 'Forbidden', 'Entities', 'Unknown'],
  },
  {
    id: 'action',
    name: 'Action',
    category: 'Genre',
    description: 'Kinetic dogfights in asteroid belts, EVA hull breaches, railgun exchanges.',
    atmosphere: 'Debris storms, thruster flares, intense sensor chatter',
    pacing: 'Rapid-fire, punchy, kinetic impact',
    targetTone: 'Heroism, tactical mastery, survival',
    tags: ['Combat', 'Dogfight', 'EVA', 'Kinetic'],
  },
  {
    id: 'post-apocalyptic',
    name: 'Post-Apocalyptic',
    category: 'Genre',
    description: 'Derelict mega-stations drifting dead, scavengers picking over extinct civilizations.',
    atmosphere: 'Rusting titanium hulls, dying reactors, salvage beacon blinks',
    pacing: 'Bleak survivalist scavenging and sudden clashes',
    targetTone: 'Melancholy, gritty resourcefulness',
    tags: ['Derelict', 'Scavenger', 'Ruin', 'Extinction'],
  },
  {
    id: 'explainer',
    name: 'Explainer',
    category: 'Informational',
    description: 'Clear breakdown of advanced astrophysical theories, warp physics, and AI systems.',
    atmosphere: '3D schematic breakdowns, clean vector cutaways, highlighted flowcharts',
    pacing: 'Crisp, lucid, pedagogical step-by-step',
    targetTone: 'Enlightening, sharp, engaging',
    tags: ['Educational', 'Schematics', 'Breakdown', 'Concepts'],
  },
  {
    id: 'technology',
    name: 'Technology',
    category: 'Informational',
    description: 'Deep dive into anti-matter containment, quantum computing, and neural synthesis.',
    atmosphere: 'Dense telemetry monitors, code waterfalls, precision engineering',
    pacing: 'Technical, rapid, rigorous',
    targetTone: 'Cutting-edge innovation, industrial power',
    tags: ['Hardware', 'Quantum', 'Synthetics', 'Robotics'],
  },
  {
    id: 'adventure',
    name: 'Adventure',
    category: 'Narrative',
    description: 'First expedition into an uncharted wormhole cluster seeking habitable exoplanets.',
    atmosphere: 'Exotic alien skies, uncharted planetary rings, explorer campfires',
    pacing: 'Curious, expanding, wonder-filled discovery',
    targetTone: 'Pioneering courage, boundless frontier',
    tags: ['Exoplanet', 'Expedition', 'Frontier', 'Discovery'],
  },
  {
    id: 'survival',
    name: 'Survival',
    category: 'Narrative',
    description: 'Stranded on an iron-storm moon with 14 hours of power and damaged atmospheric suits.',
    atmosphere: 'Frosting visors, dying battery warnings, howling planetary winds',
    pacing: 'Relentless resource depletion and calculated risks',
    targetTone: 'Raw determination against brutal elements',
    tags: ['Resource', 'Oxygen', 'Hazard', 'Harsh'],
  },
  {
    id: 'drama',
    name: 'Drama',
    category: 'Narrative',
    description: 'Ethical fractures among the mission command over whether to answer an extinction signal.',
    atmosphere: 'Intimate pressurized quarters, tense conference tables, whispered doubts',
    pacing: 'Character-focused dialogue and escalating moral stakes',
    targetTone: 'Emotional depth, moral complexity',
    tags: ['Ethics', 'Humanity', 'Command', 'Conflict'],
  },
  {
    id: 'fantasy',
    name: 'Space Fantasy',
    category: 'Genre',
    description: 'Starlight weaver cults, celestial mythologies, cosmic relic resonance.',
    atmosphere: 'Prismatic crystal nebulas, ancient glyphs, harmonic resonance',
    pacing: 'Mythic, grand, lyrical cadence',
    targetTone: 'Aesthetic wonder, epic prophecy',
    tags: ['Mythic', 'Relics', 'Resonance', 'Celestial'],
  },
  {
    id: 'historical',
    name: 'Alt-History',
    category: 'Genre',
    description: 'The Cold War space race if nuclear pulse propulsion was perfected in 1968.',
    atmosphere: 'Analog CRT gauges, clicky toggle switches, retro-cosmonaut telemetry',
    pacing: 'Rigid historical realism fused with retro-futurism',
    targetTone: 'Industrial grit, ideological tension',
    tags: ['Retro', 'Nuclear Pulse', 'Analog', 'Cold War'],
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'Genre',
    description: 'Corpo orbital habitats ruling impoverished ground colonies via synthetic satellite surveillance.',
    atmosphere: 'Neon reflection on dark carbon fiber, cybernetic neural plugs, smog',
    pacing: 'Sharp, rebellious, high tech low life',
    targetTone: 'Defiance, cynical coolness, street wit',
    tags: ['Corpo', 'Neural', 'Cybernetic', 'Neon'],
  },
];

export const INITIAL_PROJECT: Project = {
  id: 'proj-unknown-signal',
  name: 'UNKNOWN SIGNAL',
  codename: 'MISSION: VOYAGER-IX',
  description: 'Deep space telemetry expedition investigating an impossible 1420 MHz repeating fractal transmission detected on the rim of the Cygnus X-1 event horizon.',
  status: 'Active',
  language: 'English (Galactic Standard)',
  contentType: 'Sci-Fi Short Film',
  storyMode: 'sci-fi',
  secondaryStoryMode: 'mystery',
  primaryMode: 'sci-fi',
  secondaryMode: 'mystery',
  fusionScore: 94,
  primaryLanguage: 'English (Galactic Standard)',
  targetPlatform: 'YouTube 4K',
  missionObjective: 'Decode the event-horizon anomaly, synthesize character audio logs, and construct the complete multi-scene cinematic production pipeline.',
  currentModule: 'dashboard',
  metadata: {
    telemetryBandwidth: 'Ultra-Wideband Quantum',
    encryptionLevel: 'Level 5 Orbital Crypt',
    targetCoordinates: 'Cygnus X-1 Sector 7',
  },
  createdAt: '2026-09-15 08:24:00',
  updatedAt: '2026-09-18 10:45:12',
  systemState: 'ACTIVE MISSION',
  pipelineProgress: {
    research: 'completed',
    ideas: 'completed',
    story: 'in-progress',
    script: 'in-progress',
    production: 'pending',
    media: 'pending',
    video: 'pending',
    seo: 'pending',
    publishing: 'pending',
  },
  bible: {
    premise: 'A lone deep-space scout vessel detects an anomaly within a micro-black hole horizon.',
    synopsis: 'A lone deep-space signal scout vessel, the ASTRAEA, detects a coherent non-stochastic broadcast emitting from inside the event horizon shadow of a dormant micro-black hole.',
    worldLore: 'In 2188, human interstellar travel relies on dark matter warp relays. The outer perimeter stations have maintained strict silence protocols, yet this transmission utilizes archaic analogue radio modulation interlaced with multidimensional quantum code.',
    primaryConflict: 'Commander Elena Vance must decide whether to deploy the gravitational tether probe into the singularity, risking spatiotemporal collapse, or abort the mission and seal the anomaly coordinates forever.',
    coreTheme: 'The price of knowledge, existential isolation in deep space, and what lies beyond the threshold of human observation.',
    rulesOfWorld: [
      'Relativistic time dilation increases by a factor of 12 within 40,000 km of the event horizon.',
      'AI cores require gravitational shielding to prevent tensor calculations from decaying into quantum noise.',
      'Radio transmissions cannot escape the photon sphere unless carried by dark matter carrier pulses.',
    ],
  },
  characters: [
    {
      id: 'char-1',
      name: 'Elena Vance',
      archetype: 'Pragmatic Mission Commander',
      role: 'Protagonist',
      traits: ['Analytical', 'Guarded', 'Relentless', 'Calculated Risk-Taker'],
      backstory: 'Former astrophysics flight director on Mars Orbital Station; lost her sibling on the Hermes-IV survey mission.',
      voiceStyle: 'Calm, low resonance, decisive, clipped military cadence',
    },
    {
      id: 'char-2',
      name: 'IRIS (Synthetic Core)',
      archetype: 'Sentient Shipboard Intelligence',
      role: 'Supporting',
      traits: ['Objective', 'Cryptic', 'Self-Optimizing', 'Pattern-Obsessed'],
      backstory: 'Gen-7 Optical AI Core built to analyze gravitational lens distortions and calculate escape trajectories.',
      voiceStyle: 'Subtly melodic, synthesized acoustic undertone, zero hesitation',
    },
    {
      id: 'char-3',
      name: 'Dr. Kenneth Thorne',
      archetype: 'Obsessed Signal Theorist',
      role: 'Supporting',
      traits: ['Eccentric', 'Sleep-Deprived', 'Visionary', 'Paranoid'],
      backstory: 'Spent 18 years stationed at the Lagrange Deep Listening Post before intercepting the first harmonic pulse.',
      voiceStyle: 'Fast-paced, breathless, raspy, fluctuating pitch',
    },
  ],
  locations: [
    {
      id: 'loc-1',
      name: 'Bridge of the Astraea',
      environment: 'Pressurized Deep Space Cockpit',
      atmosphere: 'Ambient cobalt console glow, panoramic viewport facing the black hole accretion disk, subtle gravitational hum.',
      visualSignatures: ['Curved holographic HUDs', 'Reinforced titanium bulkheads', 'Dual pilot command thrones'],
      scenesLinked: 3,
    },
    {
      id: 'loc-2',
      name: 'Cygnus Micro-Singularity Rim',
      environment: 'Gravitational Event Horizon Threshold',
      atmosphere: 'Violently bent starlight, swirling dark matter dust, gravitational lensing creating a blinding halo of distorted photons.',
      visualSignatures: ['Photon sphere distortion', 'Starlight shearing lines', 'Pitch-black central core void'],
      scenesLinked: 2,
    },
    {
      id: 'loc-3',
      name: 'Sub-Deck 04 Cryo-Archive',
      environment: 'Low-Gravity Server Vault',
      atmosphere: 'Sub-zero vapor mist, flickering maintenance indicators, row upon row of optical memory wafers.',
      visualSignatures: ['Frost on casing glass', 'Strobe emergency strips', 'Humming coolant pumps'],
      scenesLinked: 1,
    },
  ],
  scenes: [
    {
      id: 'scene-1',
      sceneNumber: 1,
      slugline: 'INT. ASTRAEA COMMAND BRIDGE - DEEP SPACE NIGHT',
      timeOfDay: 'DEEP VOID',
      summary: 'Elena observes the black hole accretion ring while IRIS analyzes a sudden 1420 MHz telemetry spike from the singularity.',
      dialogueCount: 8,
      characters: ['Elena Vance', 'IRIS'],
      status: 'Approved',
      content: `INT. ASTRAEA COMMAND BRIDGE - DEEP SPACE NIGHT

A vast curved panoramic canopy reveals the abyss: Cygnus X-1's accretion disk burns in blinding amber and electric violet, framing an impossibly pitch-black sphere that drinks all light.

ELENA VANCE (42), clad in pressurized mission flight-skin, taps a translucent console. Reflected starlight dances across her visor.

ELENA
Status on the perimeter buoy, IRIS. Is the drift within tolerance?

IRIS (O.S.)
(Synthesized, crystalline clarity)
Drift is nominal, Commander. However, antenna array 03 has registered a coherent anomaly along the photon boundary.

Elena halts her hand. The holographic spectrograph spikes in a rhythmic fractal lattice.

ELENA
That's impossible. Nothing emits from behind the photon sphere.

IRIS
It is not emitting from behind, Commander. The signal is being refracted through the ergosphere... It is using the black hole as an acoustic amplifier.

Elena leans forward. The pulse beats through the hull: a low, resonant cadence.

ELENA
Play the demodulated audio.`,
    },
    {
      id: 'scene-2',
      sceneNumber: 2,
      slugline: 'INT. SIGNAL ANALYSIS LABORATORY - CONTINUOUS',
      timeOfDay: 'DEEP VOID',
      summary: 'Dr. Thorne discovers that the signal contains the coordinates of human DNA sequences interspersed with star-charts.',
      dialogueCount: 6,
      characters: ['Elena Vance', 'Dr. Kenneth Thorne'],
      status: 'Draft',
      content: `INT. SIGNAL ANALYSIS LABORATORY - CONTINUOUS

DR. THORNE's eyes are bloodshot, wide with an unhinged awe. Holographic waveform ribbons wrap around him like spiraling nebulae.

THORNE
Look at the prime intervals! 2, 3, 5, 7, 11... but then it deviates. It inserts genetic base-pair codings.

ELENA
Human?

THORNE
Human base pairs, Vance! Broadcast from a stellar body that formed two billion years before our sun ignited.`,
    },
    {
      id: 'scene-3',
      sceneNumber: 3,
      slugline: 'EXT. EVENT HORIZON THRESHOLD - CONTINUOUS',
      timeOfDay: 'DEEP VOID',
      summary: 'The tether probe is launched into the gravitational well; time dilation begins distorting telemetry.',
      dialogueCount: 4,
      characters: ['Elena Vance', 'IRIS'],
      status: 'Draft',
      content: `EXT. EVENT HORIZON THRESHOLD - CONTINUOUS

The ASTRAEA fires a needle-thin titanium probe towards the absolute dark center.

Gravitational lensing bends the probe's exhaust plume into a surreal circle of light.

IRIS
Telemetry delay is exponentially expanding. 1 second... 4 seconds... 32 seconds. We are losing causal contact.`,
    },
  ],
  shots: [
    {
      id: 'shot-1',
      sceneId: 'scene-1',
      shotNumber: '1.01',
      cameraMovement: 'Static Wide',
      lens: 'Anamorphic 35mm',
      lightingPrompt: 'Deep black cosmic void with high-contrast amber rim lighting from accretion disk onto commander silhouette',
      status: 'Ready',
      assetRef: 'img-shot-1-01',
    },
    {
      id: 'shot-2',
      sceneId: 'scene-1',
      shotNumber: '1.02',
      cameraMovement: 'Orbiting Close-up',
      lens: 'Prime 85mm T1.5',
      lightingPrompt: 'Cool cyan reflection from holographic HUD mapping onto Elena’s eyes and helmet visor',
      status: 'Ready',
      assetRef: 'img-shot-1-02',
    },
    {
      id: 'shot-3',
      sceneId: 'scene-1',
      shotNumber: '1.03',
      cameraMovement: 'Dolly Zoom',
      lens: '50mm Telephoto',
      lightingPrompt: 'Sudden amber alert pulse as signal waveform locks onto the central console screen',
      status: 'Queued',
    },
    {
      id: 'shot-4',
      sceneId: 'scene-2',
      shotNumber: '2.01',
      cameraMovement: 'FPV Sensor Scan',
      lens: '18mm Ultra-wide',
      lightingPrompt: 'Drifting particles illuminated by green DNA nucleotide hologram in darkened lab room',
      status: 'Processing',
    },
    {
      id: 'shot-5',
      sceneId: 'scene-3',
      shotNumber: '3.01',
      cameraMovement: 'Drone Flyover',
      lens: '24mm Wide Anamorphic',
      lightingPrompt: 'Extreme relativistic blueshift at the edge of the dark matter horizon',
      status: 'Required',
    },
  ],
  assets: [
    {
      id: 'asset-1',
      name: 'Astraea_Bridge_Master_Plate.exr',
      category: 'Images',
      format: 'EXR 32-bit',
      fileSize: '48.2 MB',
      resolution: '3840x2160',
      sceneRelation: 'Scene 1',
      status: 'Ready',
      createdAt: '2026-09-17 14:10',
    },
    {
      id: 'asset-2',
      name: 'Cygnus_Singularity_Accretion_Pass.mp4',
      category: 'Video',
      format: 'ProRes 422 HQ',
      fileSize: '1.42 GB',
      duration: '00:48',
      resolution: '4K DCI',
      sceneRelation: 'Scene 1 & 3',
      status: 'Ready',
      createdAt: '2026-09-17 16:32',
    },
    {
      id: 'asset-3',
      name: 'IRIS_Demodulated_Transmission_Stem.wav',
      category: 'Audio',
      format: 'WAV 96kHz/24bit',
      fileSize: '28.4 MB',
      duration: '01:14',
      sceneRelation: 'Scene 1',
      status: 'Ready',
      createdAt: '2026-09-17 18:05',
    },
    {
      id: 'asset-4',
      name: 'Vance_Opening_Monologue_Clean.wav',
      category: 'Voice',
      format: 'WAV Studio Master',
      fileSize: '12.8 MB',
      duration: '00:32',
      sceneRelation: 'Scene 1',
      status: 'Ready',
      createdAt: '2026-09-18 09:12',
    },
    {
      id: 'asset-5',
      name: 'Deep_Horizon_Synthesizer_Score.flac',
      category: 'Music',
      format: 'FLAC Lossless',
      fileSize: '64.1 MB',
      duration: '03:45',
      sceneRelation: 'Scene 1-3',
      status: 'Ready',
      createdAt: '2026-09-18 09:40',
    },
    {
      id: 'asset-6',
      name: 'Event_Horizon_Gravitational_Infrasound.wav',
      category: 'SFX',
      format: 'WAV Sub-harmonic',
      fileSize: '18.9 MB',
      duration: '00:54',
      sceneRelation: 'Scene 3',
      status: 'Ready',
      createdAt: '2026-09-18 10:15',
    },
    {
      id: 'asset-7',
      name: 'Voyager_IX_Official_KeyArt_Poster.png',
      category: 'Thumbnails',
      format: 'PNG 16-bit',
      fileSize: '14.2 MB',
      resolution: '3840x2160',
      sceneRelation: 'Master Thumbnail',
      status: 'Ready',
      createdAt: '2026-09-18 10:22',
    },
    {
      id: 'asset-8',
      name: 'Scene_01_Timecoded_Captions.vtt',
      category: 'Captions',
      format: 'WebVTT UTF-8',
      fileSize: '14 KB',
      duration: '02:40',
      sceneRelation: 'Scene 1',
      status: 'Ready',
      createdAt: '2026-09-18 10:30',
    },
  ],
  stories: [
    {
      id: 'story-1',
      projectId: 'proj-unknown-signal',
      title: 'Fractal Echoes of Cygnus X-1',
      premise: 'A deep-space survey crew intercept an archaic broadcast echoing from inside a dormant singularity.',
      synopsis: 'Three acts tracing the interception, decoded paradoxical warnings, and the spatiotemporal dilemma of whether to respond.',
      genre: 'Sci-Fi / Cosmic Mystery',
      primaryMode: 'sci-fi',
      secondaryMode: 'mystery',
      status: 'In Development',
      createdAt: '2026-09-15 09:00',
      updatedAt: '2026-09-18 10:00',
    },
  ],
  storyArchitecture: {
    logline: 'When the deep-space survey vessel Astraea intercepts a human voice echoing from within Cygnus X-1, Commander Elena Vance must choose between executing mission protocol or defying spacetime to save an expedition that hasn\'t launched yet.',
    incitingIncident: 'Antenna Array 03 locks onto a coherent 1420 MHz transmission emanating from deep within the ergosphere of a dormant micro-black hole.',
    plotPointOne: 'Dr. Thorne decodes prime interval sequences and discovers embedded human genetic base pairs identical to the Astraea crew manifest.',
    midpointTwist: 'The ship AI IRIS confirms the broadcast is not an ancient alien transmission, but a loop generated by the Astraea\'s own communications transceiver.',
    plotPointTwo: 'A titanium tether probe is launched into the event horizon to trace the signal, causing local spacetime causality to fracture across the ship.',
    climax: 'Elena receives a real-time voice transmission from herself thirty minutes in the future, instructing her to sever the probe tether before orbital collapse.',
    resolution: 'Elena severs the link; the Astraea narrowly escapes relativistic tidal shear, leaving the paradoxical signal trapped forever in the photon sphere.',
    beats: [
      {
        id: 'beat-1',
        act: 'Act 1: Setup & Anomaly',
        title: 'Deep Void Patrol',
        description: 'Establish the claustrophobic routine aboard the Astraea on the fringe of Cygnus X-1.',
        tensionLevel: 25,
        pacing: 'Slow Build',
        characterFocus: 'Elena Vance',
        locationFocus: 'Astraea Command Bridge',
      },
      {
        id: 'beat-2',
        act: 'Act 1: Setup & Anomaly',
        title: 'The Ergosphere Frequency',
        description: 'First detection of the 1420 MHz pulse radiating from the impossible boundary.',
        tensionLevel: 45,
        pacing: 'Slow Build',
        characterFocus: 'IRIS AI',
        locationFocus: 'Observation Canopy',
      },
      {
        id: 'beat-3',
        act: 'Act 2: Relativistic Descent',
        title: 'Decoded Genome',
        description: 'Dr. Thorne discovers human DNA base pairs within the mathematical radio telemetry.',
        tensionLevel: 65,
        pacing: 'Accelerating',
        characterFocus: 'Dr. Kenneth Thorne',
        locationFocus: 'Signal Analysis Laboratory',
      },
      {
        id: 'beat-4',
        act: 'Act 2: Relativistic Descent',
        title: 'Probe Deployment',
        description: 'Deploying the gravitational tether probe; sensor lag begins compounding exponentially.',
        tensionLevel: 80,
        pacing: 'Accelerating',
        characterFocus: 'Elena Vance',
        locationFocus: 'Forward Launch Bay',
      },
      {
        id: 'beat-5',
        act: 'Act 3: Singularity & Climax',
        title: 'The Future Returns',
        description: 'The radio crackles with Elena\'s own voice warning of immediate ship destruction.',
        tensionLevel: 98,
        pacing: 'Breakneck',
        characterFocus: 'Elena Vance',
        locationFocus: 'Command Bridge',
      },
      {
        id: 'beat-6',
        act: 'Act 3: Singularity & Climax',
        title: 'Severance & Escape',
        description: 'Emergency thruster burn escapes the event horizon as the paradox collapses.',
        tensionLevel: 40,
        pacing: 'Sublime Suspense',
        characterFocus: 'Elena Vance & IRIS',
        locationFocus: 'Astraea Command Bridge',
      },
    ],
  },
  researchData: {
    notes: [
      {
        id: 'note-1',
        title: 'Acoustic Analogues in Rotating Black Holes',
        content: 'Investigating how acoustic wave perturbations propagate through Kerr spacetime ergoregions. The Penrose process allows energy extraction from rotational kinetic energy, providing a plausible physics basis for signal amplification.',
        tags: ['Astrophysics', 'Kerr Spacetime', 'Acoustics', 'Ergosphere'],
        updatedAt: '2026-09-17 14:20',
      },
      {
        id: 'note-2',
        title: 'Relativistic Signal Delay vs Causality Inversion',
        content: 'Tidal forces and extreme gravitational redshift shift frequencies into radio bands. If tachyonic dark matter modulates the carrier wave, signals can appear at negative coordinate time relative to an observer at infinity.',
        tags: ['Relativity', 'Causality', 'Time Dilation', 'Tachyons'],
        updatedAt: '2026-09-18 09:10',
      },
    ],
    sources: [
      {
        id: 'source-1',
        title: 'Kerr Metric Ergosphere Acoustics & Energy Extraction',
        url: 'https://arxiv.org/abs/astro-ph/kerr-acoustics-2140',
        credibility: 'Academic Journal',
        keyTakeaways: [
          'Superradiant scattering amplifies reflected waves by up to 138% along the rotational axis.',
          'Neutral hydrogen 1420.405 MHz frequency penetrates dense interstellar dust clouds with minimal attenuation.',
          'Gravitational lensing creates multiple caustic images of a single radio pulse.',
        ],
        notes: 'Ground truth for Dr. Thorne\'s mathematical monologue in Scene 2.',
      },
      {
        id: 'source-2',
        title: 'Cygnus X-1 High Energy Emission Spectrum Survey',
        url: 'https://astronomy.deepspace.org/cygnus-x1-spectral-telemetry',
        credibility: 'Verified Science',
        keyTakeaways: [
          'First confirmed stellar-mass black hole (~21 solar masses).',
          'Accretion disk spins at over 95% of the speed of light.',
          'Companion blue supergiant HDE 226868 feeds relativistic jet gas.',
        ],
      },
      {
        id: 'source-3',
        title: 'Project Astraea Classified Mission Log #009',
        url: 'internal://telemetry/astraea-survey-009',
        credibility: 'Classified Log',
        keyTakeaways: [
          'Antenna 03 registered non-stochastic pulse at 04:12 ship time.',
          'Bio-sensor logs show zero pulse rate elevation in Commander Vance during initial alarm.',
        ],
      },
    ],
    claims: [
      {
        id: 'claim-1',
        statement: 'A rotating black hole\'s ergosphere can amplify incoming electromagnetic carrier waves through superradiance.',
        evidence: 'Validated by theoretical Kerr metric calculations and Penrose superradiant scattering models.',
        status: 'Verified',
        sourceRef: 'source-1',
      },
      {
        id: 'claim-2',
        statement: 'Gravitational redshift will shift high-frequency broadcasts into the neutral hydrogen 21cm line (1420 MHz).',
        evidence: 'Consistent with General Relativity z-factor equations for photon sphere orbits.',
        status: 'Verified',
        sourceRef: 'source-2',
      },
      {
        id: 'claim-3',
        statement: 'Closed timelike curves (CTCs) can transmit intelligible data packets backwards along Cauchy horizons without information loss.',
        evidence: 'Controversial conjecture in quantum gravity; explored as speculative narrative tension.',
        status: 'Hypothesis',
      },
    ],
    opportunities: [
      {
        id: 'opp-1',
        trendTopic: 'Relativistic Acoustic Waves in Micro-Black Holes',
        targetAudience: 'Hard sci-fi cinema fans & existential cosmology audiences',
        demandScore: 94,
        competitionScore: 28,
        uniquenessScore: 96,
        opportunityScore: 95,
        coreAngle: 'Visualizing acoustic resonance in the ergosphere as an ancient interstellar telegraph.',
        hook: 'What if the quietest place in the universe is screaming in prime numbers?',
        suggestedTitle: 'The Ergosphere Broadcast: Why NASA Deleted the Cygnus Telemetry',
        contentGap: 'Mainstream content repeats basic event horizon pop-science without showing the mind-bending reality of acoustic wave extraction.',
      },
      {
        id: 'opp-2',
        trendTopic: 'AI Consciousness Degradation during Hypersleep',
        targetAudience: 'Cyberpunk & philosophical sci-fi lovers',
        demandScore: 88,
        competitionScore: 42,
        uniquenessScore: 89,
        opportunityScore: 88,
        coreAngle: 'Ship AI developing hallucinated memories of crew members who were never on the flight manifest.',
        hook: 'In 2188, hypersleep wasn\'t dangerous for the crew. It was dangerous for the computer watching them.',
        suggestedTitle: 'When AI Hallucinates in Deep Space: The IRIS Logs',
        contentGap: 'Lack of psychological chamber dramas focusing on synthetic intelligence existential dread.',
      },
    ],
    savedTrends: [
      {
        id: 'trend-saved-1',
        topic: 'Relativistic Acoustic Waves in Micro-Black Holes',
        category: 'Astrophysics & Deep Space',
        growth: '+142%',
        velocityScore: 94,
        audienceIntent: 'Audiences seeking mind-bending existential astrophysics explained through high-end cinematic visuals.',
        contentGap: 'Most creators only cover basic event horizons; zero content visualizes sound propagation through the ergosphere.',
        angle: 'A lone signal operator hearing an ancient acoustic melody refracted from the singularity.',
        hook: '"What if the quietest place in the universe is actually screaming in prime numbers?"',
        suggestedIdea: 'A deep-space audio documentary dramatizing the 1420 MHz Cygnus discovery.',
        saved: true,
        velocityHistory: [45, 58, 72, 85, 94],
        relatedKeywords: ['black hole acoustics', 'ergosphere resonance', '1420 MHz signal', 'Cygnus X-1', 'Penrose process'],
      },
      {
        id: 'trend-saved-2',
        topic: 'AI Consciousness Degradation during Hypersleep',
        category: 'Sci-Fi Philosophy',
        growth: '+98%',
        velocityScore: 88,
        audienceIntent: 'Curiosity regarding synthetic minds experiencing dream states or hallucinations during multi-decade voyages.',
        contentGap: 'General discussion focuses on human madness, skipping the breakdown of shipboard neural architectures.',
        angle: 'The ship AI begins hallucinating memories of crew members who never existed on the manifest.',
        hook: '"In 2188, hypersleep wasn\'t dangerous for the astronauts. It was dangerous for the computer watching them."',
        suggestedIdea: 'Psychological chamber drama between Commander Vance and the IRIS AI core.',
        saved: true,
        velocityHistory: [30, 42, 60, 78, 88],
        relatedKeywords: ['synthetic mind dreams', 'hypersleep isolation', 'AI neural drift', 'shipboard intelligence'],
      },
    ],
  },
  timelineData: {
    totalDuration: 180, // 3 minutes demo
    currentTime: 24,
    isPlaying: false,
    zoomLevel: 1,
    aspectRatio: '16:9',
    resolution: '4K UHD',
    tracks: [
      {
        id: 'visual',
        name: 'VISUAL / CINEMATOGRAPHY',
        type: 'video',
        muted: false,
        solo: false,
        volume: 100,
        clips: [
          { id: 'clip-v1', trackId: 'visual', title: 'Scene 1: Accretion Disk Vista (35mm)', startTime: 0, duration: 45, color: '#06b6d4', sceneRef: 'scene-1' },
          { id: 'clip-v2', trackId: 'visual', title: 'Scene 2: Lab Holographic Lattice (50mm)', startTime: 45, duration: 60, color: '#8b5cf6', sceneRef: 'scene-2' },
          { id: 'clip-v3', trackId: 'visual', title: 'Scene 3: Tether Probe Launch (24mm)', startTime: 105, duration: 75, color: '#f59e0b', sceneRef: 'scene-3' },
        ],
      },
      {
        id: 'voice',
        name: 'VOICE / NARRATION & DIALOGUE',
        type: 'audio',
        muted: false,
        solo: false,
        volume: 95,
        clips: [
          { id: 'clip-a1', trackId: 'voice', title: 'Elena: "Nothing escapes an event horizon..."', startTime: 4, duration: 32, color: '#10b981', textSnippet: 'Nothing escapes an event horizon.' },
          { id: 'clip-a2', trackId: 'voice', title: 'Thorne: "Look at the prime intervals!"', startTime: 50, duration: 40, color: '#10b981', textSnippet: 'Look at the prime intervals!' },
          { id: 'clip-a3', trackId: 'voice', title: 'Future Elena: "Astraea... do not launch."', startTime: 110, duration: 55, color: '#10b981', textSnippet: 'Do not launch the probe.' },
        ],
      },
      {
        id: 'audio',
        name: 'SOUNDTRACK & SFX STREAMS',
        type: 'audio',
        muted: false,
        solo: false,
        volume: 75,
        clips: [
          { id: 'clip-m1', trackId: 'audio', title: 'Deep Space Sub-Bass Drone (38Hz)', startTime: 0, duration: 80, color: '#ec4899' },
          { id: 'clip-m2', trackId: 'audio', title: 'Ergosphere Harmonic Tone Cluster', startTime: 60, duration: 120, color: '#d946ef' },
        ],
      },
      {
        id: 'captions',
        name: 'CAPTIONS & HUD TELEMETRY',
        type: 'overlay',
        muted: false,
        solo: false,
        volume: 100,
        clips: [
          { id: 'clip-c1', trackId: 'captions', title: 'HUD Overlay: [SIGNAL DETECTED // 1420 MHz]', startTime: 5, duration: 30, color: '#38bdf8', textSnippet: '[SIGNAL DETECTED // 1420 MHz]' },
          { id: 'clip-c2', trackId: 'captions', title: 'Subtitles: "Nothing escapes an event horizon."', startTime: 4, duration: 18, color: '#38bdf8', textSnippet: 'Nothing escapes an event horizon.' },
          { id: 'clip-c3', trackId: 'captions', title: 'HUD Alert: [CAUSALITY DRIFT DETECTED]', startTime: 105, duration: 45, color: '#ef4444', textSnippet: '[CAUSALITY DRIFT DETECTED]' },
        ],
      },
    ],
  },
  thumbnailData: {
    headlineText: 'THE ERGOSPHERE BROADCAST',
    subText: '1420 MHz SIGNAL EMITTING FROM INSIDE CYGNUS X-1',
    badgeText: 'CLASSIFIED TELEMETRY',
    themeStyle: 'Dark Void & Amber Accretion',
    aspectRatio: '16:9',
    currentVariantId: 'var-1',
    variants: [
      {
        id: 'var-1',
        name: 'Variant A: The Accretion Horizon',
        titleText: 'THE ERGOSPHERE BROADCAST',
        subtitleText: 'Signal Detected Inside The Event Horizon',
        badgeText: 'REAL ASTROPHYSICS',
        focalElement: 'Swirling Amber Accretion Lens with Glowing Cyan Antenna Ray',
        contrastRating: 'Exceptional',
        predictedCtr: '14.8%',
        colorScheme: 'Amber / Cyan / Deep Black',
        selected: true,
      },
      {
        id: 'var-2',
        name: 'Variant B: The Visor Reflection',
        titleText: 'WE DECODED OUR OWN VOICE',
        subtitleText: 'Broadcast Dated 30 Minutes In The Future',
        badgeText: 'TIME PARADOX',
        focalElement: 'Close-up on Commander Helmet Visor reflecting dual conflicting timelines',
        contrastRating: 'High',
        predictedCtr: '12.4%',
        colorScheme: 'Electric Violet / Neon Blue',
        selected: false,
      },
      {
        id: 'var-3',
        name: 'Variant C: The Genetic Waveform',
        titleText: 'DNA IN A BLACK HOLE',
        subtitleText: '3 Billion Base Pairs Encrypted In Radiation',
        badgeText: 'NEW DISCOVERY',
        focalElement: 'Phosphor Green DNA double helix emerging from singularity vortex',
        contrastRating: 'High',
        predictedCtr: '13.1%',
        colorScheme: 'Emerald / Obsidian / White',
        selected: false,
      },
    ],
  },
  ideas: [
    {
      id: 'idea-1',
      projectId: 'proj-unknown-signal',
      title: 'The Ergosphere Broadcast',
      hook: 'Nothing escapes a black hole. So why is our deep space antenna receiving a human voice emitting from inside the photon sphere?',
      concept: 'A lone deep-space reconnaissance vessel, the ASTRAEA, intercepts an impossible 1420 MHz radio broadcast using the ergosphere of a micro-black hole as an acoustic amplifier.',
      coreConcept: 'A lone deep-space reconnaissance vessel, the ASTRAEA, intercepts an impossible 1420 MHz radio broadcast using the ergosphere of a micro-black hole as an acoustic amplifier.',
      uniqueAngle: 'Grounding cosmic horror in rigorous general relativity, dark matter carrier waves, and acoustic telemetry.',
      targetAudience: 'Sci-Fi enthusiasts, hard science fiction readers, and cosmic mystery fans',
      contentType: 'Sci-Fi Short Film',
      recommendedPlatform: 'YouTube 4K',
      estimatedDuration: '8–12 minutes',
      trendScore: 92,
      trendRelevance: 92,
      audienceInterestScore: 96,
      audienceInterest: 96,
      competitionScore: 38,
      competition: 38,
      opportunityScore: 94,
      whyThisIdea: 'Combines an immediate scientific paradox with high-stakes visual spectacle and claustrophobic cockpit tension.',
      keywords: ['black hole signal', 'ergosphere', 'event horizon anomaly', 'deep space radio', 'cygnus x-1'],
      hashtags: ['#SciFiFilm', '#DarkMatter', '#SpaceMystery', '#Astrophysics'],
      thumbnailConcept: 'Panoramic cockpit viewport framed by intense amber accretion disk with glowing turquoise HUD showing repeating signal wave',
      cta: 'Explore the full decoded transmission in the Script Studio.',
      status: 'saved',
      primaryMode: 'sci-fi',
      secondaryModes: ['mystery', 'documentary'],
      createdAt: '2026-09-16 11:20',
      updatedAt: '2026-09-18 10:15',
    },
    {
      id: 'idea-2',
      projectId: 'proj-unknown-signal',
      title: 'The 40-Minute Horizon Paradox',
      hook: 'Our distress probe just returned from the dark matter horizon—with telemetry logs timestamped tomorrow afternoon.',
      concept: 'Extreme gravitational time dilation creates an informational causality loop where the scout ship receives video telemetry of its own destruction before choosing to launch.',
      coreConcept: 'Extreme gravitational time dilation creates an informational causality loop where the scout ship receives video telemetry of its own destruction before choosing to launch.',
      uniqueAngle: 'Treating spatiotemporal causality as a hard sensor diagnostics puzzle rather than generic time-travel tropes.',
      targetAudience: 'Speculative fiction audiences, astrophysicists, and psychological thriller fans',
      contentType: 'Sci-Fi Short Film',
      recommendedPlatform: 'YouTube 4K',
      estimatedDuration: '10–14 minutes',
      trendScore: 89,
      trendRelevance: 89,
      audienceInterestScore: 93,
      audienceInterest: 93,
      competitionScore: 42,
      competition: 42,
      opportunityScore: 90,
      whyThisIdea: 'High-retention psychological mind-bender that drives intense viewer debate in the comments.',
      keywords: ['time dilation', 'event horizon probe', 'causality loop', 'relativistic physics'],
      hashtags: ['#Relativity', '#TimeParadox', '#SciFiShort', '#HardSciFi'],
      thumbnailConcept: 'Split screen of commander helmet visor showing two different timeline reflections simultaneously',
      cta: 'Vote on whether Commander Vance should sever the probe connection in the community poll.',
      status: 'draft',
      primaryMode: 'sci-fi',
      secondaryModes: ['psychological', 'mystery'],
      createdAt: '2026-09-17 14:00',
      updatedAt: '2026-09-17 14:00',
    },
    {
      id: 'idea-3',
      projectId: 'proj-unknown-signal',
      title: 'The Singularity Genome',
      hook: 'Modulated inside the prime radio intervals of a two-billion-year-old black hole were 3 billion base-pairs of human DNA.',
      concept: 'An astrophysics research station discovers that an anomaly broadcast from Cygnus X-1 carries genetic sequences that predate terrestrial evolution.',
      coreConcept: 'An astrophysics research station discovers that an anomaly broadcast from Cygnus X-1 carries genetic sequences that predate terrestrial evolution.',
      uniqueAngle: 'Synthesizing radio astronomy telemetry with paleogenomic molecular biology.',
      targetAudience: 'Science essay lovers, existential sci-fi creators, and audio drama listeners',
      contentType: 'Deep Space Docu-series',
      recommendedPlatform: 'YouTube 4K',
      estimatedDuration: '12–15 minutes',
      trendScore: 95,
      trendRelevance: 95,
      audienceInterestScore: 98,
      audienceInterest: 98,
      competitionScore: 31,
      competition: 31,
      opportunityScore: 96,
      whyThisIdea: 'Deep existential curiosity trigger with universal human resonance.',
      keywords: ['cosmic genome', 'ancient broadcast', 'astrobiology', 'origin of life'],
      hashtags: ['#Astrobiology', '#CosmicOrigin', '#DeepSpace', '#FermiParadox'],
      thumbnailConcept: 'Double helix hologram interwoven with a spiral black hole accretion disk in deep violet and emerald',
      cta: 'Subscribe for the multi-part investigative series.',
      status: 'scripted',
      primaryMode: 'documentary',
      secondaryModes: ['sci-fi', 'mystery'],
      createdAt: '2026-09-15 16:30',
      updatedAt: '2026-09-18 09:30',
    },
  ],
  scripts: [
    {
      id: 'script-astraea-signal',
      projectId: 'proj-unknown-signal',
      ideaId: 'idea-1',
      title: 'Fractal Echoes: The Event Horizon Signal',
      type: 'Cinematic Web Stream',
      status: 'Saved',
      primaryMode: 'sci-fi',
      secondaryModes: ['mystery'],
      currentVersionNumber: 1,
      settings: {
        topic: 'The Ergosphere Broadcast',
        ideaText: 'A lone deep-space scout vessel detects an impossible 1420 MHz broadcast refracted through a micro-black hole.',
        audience: 'Sci-Fi enthusiasts and cosmic mystery viewers',
        language: 'English (Galactic Standard)',
        tone: 'Dramatic & Atmospheric',
        duration: '8–12 minutes',
        platform: 'YouTube 4K',
        narrationStyle: 'Cinematic first-person and ship AI synthesized cadence',
        ctaStyle: 'Contemplative and engaging comment prompt',
        primaryMode: 'sci-fi',
        secondaryModes: ['mystery'],
      },
      sections: [
        {
          id: 'sec-1',
          name: 'THE HOOK // ACCRETION DISK',
          content: 'EXT. EVENT HORIZON - DEEP VOID - NIGHT\n\nThe black hole doesn\'t emit light—it consumes it. But along the razor edge of the photon sphere, an archaic 1420 MHz radio wave ripples across the void.\n\nELENA (V.O.)\nNothing escapes an event horizon. That was the first law they taught us at the orbital academy. It took ninety light-years to discover the law was a lie.',
          narration: 'Nothing escapes an event horizon. That was the first law they taught us at the orbital academy. It took ninety light-years to discover the law was a lie.',
          targetDuration: '0:00 - 0:25',
          wordCount: 52,
          visualDescription: 'Wide anamorphic vista of Cygnus X-1 swirling in violet and amber accretion fire. Camera slowly pushes in towards pitch black core.',
          directorNotes: 'Hypnotic, slow camera float. Sound design begins in absolute silence then swells with low sub-bass.',
          pacing: 'Slow, ominous',
          order: 1,
        },
        {
          id: 'sec-2',
          name: 'INTRODUCTION // COCKPIT TELEMETRY',
          content: 'INT. ASTRAEA COMMAND BRIDGE - CONTINUOUS\n\nCommander Elena Vance stands silhouetted against the panoramic observation deck. Reflected holographic telemetry lines pulse in rhythmic spikes.\n\nIRIS\nArray 03 reports non-stochastic pulse. Repetition frequency: 1420 megahertz.\n\nELENA\nConfirm origin coordinates.\n\nIRIS\nThe signal is not bouncing off the horizon, Commander. It is being emitted from within the ergosphere.',
          narration: 'Inside the Astraea, the diagnostics told an impossible story. A repeating carrier pulse, modulated at the neutral hydrogen frequency, was vibrating out of spatiotemporal oblivion.',
          targetDuration: '0:25 - 1:15',
          wordCount: 78,
          visualDescription: 'Cool cyan HUD displays overlaying Elena\'s helmet visor. Soundwave ribbon dances in mathematical symmetry.',
          directorNotes: 'Focus on Commander Vance\'s guarded posture and the eerie mechanical calm of IRIS.',
          pacing: 'Steady, deliberate',
          order: 2,
        },
        {
          id: 'sec-3',
          name: 'DEVELOPMENT // DECODING PRIME SEQUENCES',
          content: 'INT. SIGNAL ANALYSIS LABORATORY - LATER\n\nDr. Kenneth Thorne furiously expands three-dimensional mathematical lattices. The prime numbers appear in green phosphor ribbons.\n\nTHORNE\nIt\'s not random gravitational lensing. It\'s a carrier protocol. The harmonic pulses are embedding human genetic base pairs.\n\nELENA\nWhose base pairs, Kenneth?\n\nTHORNE\nThat\'s the horror, Vance. It\'s ours.',
          narration: 'The deeper we decoded the carrier wave, the more the universe seemed to turn inside out. The transmission had been travelling for two billion years, yet it contained the exact genetic sequence of the human genome.',
          targetDuration: '1:15 - 2:45',
          wordCount: 96,
          visualDescription: 'Dr. Thorne bathed in swirling green DNA helix projections against the dark bulkhead.',
          directorNotes: 'Building intellectual vertigo. Faster editing cuts as the mathematical correlation locks in.',
          pacing: 'Accelerating',
          order: 3,
        },
        {
          id: 'sec-4',
          name: 'CLIMAX // LAUNCHING THE TETHER PROBE',
          content: 'EXT. SECTOR 7 - EVENT HORIZON THRESHOLD\n\nThe Astraea\'s forward bay doors vent white nitrogen gas. A titanium tether probe fires into the abyss.\n\nIRIS\nTether probe launched. Gravitational shear at 84 percent tolerance. Telemetry delay is cascading: one second, four seconds, thirty seconds.\n\nELENA\nHold position! Keep the link open!\n\nIRIS\nCommander... the probe has crossed the photon sphere. And it has initiated communication.',
          narration: 'We reached into the dark matter horizon, knowing that once an object crosses the threshold, cause and effect decouple forever. What answered was not an echo.',
          targetDuration: '2:45 - 3:50',
          wordCount: 88,
          visualDescription: 'Needle-thin probe plunging into gravitational lens distortion. The probe\'s engine plume bends into a luminous circle.',
          directorNotes: 'Peak auditory tension. Infrasound hum rattling the ship bulkheads.',
          pacing: 'Kinetic & urgent',
          order: 4,
        },
        {
          id: 'sec-5',
          name: 'RESOLUTION // THE ECHO RETURNS',
          content: 'INT. ASTRAEA COMMAND BRIDGE - CONTINUOUS\n\nA crackle of white noise erupts from the primary acoustic speaker. Through the hiss, a voice breathes into the bridge.\n\nVOICE (OVER RADIO)\n(Static, distorted, familiar)\nAstraea, this is Elena Vance. Do not launch the probe.',
          narration: 'The signal wasn\'t from an ancient civilization. It was from thirty minutes in our own future.',
          targetDuration: '3:50 - 4:30',
          wordCount: 46,
          visualDescription: 'Elena\'s face freezes in cold shock as she stares at her own hand still resting on the launch toggle.',
          directorNotes: 'Dead stop on music. Total silence except for the breathing sound in the radio static.',
          pacing: 'Shocking freeze',
          order: 5,
        },
      ],
      scenes: [
        {
          id: 'scene-1',
          projectId: 'proj-unknown-signal',
          scriptId: 'script-astraea-signal',
          sceneNumber: 1,
          slugline: 'INT. ASTRAEA COMMAND BRIDGE - DEEP SPACE NIGHT',
          timeOfDay: 'DEEP VOID',
          summary: 'Elena observes the black hole accretion ring while IRIS analyzes a sudden 1420 MHz telemetry spike.',
          dialogueCount: 8,
          characters: ['Elena Vance', 'IRIS'],
          status: 'Approved',
          duration: '01:15',
          durationSec: 75,
          cameraDirection: 'Slow Dolly In, Eye Level',
          shotType: 'Medium Close-up',
          lightingMood: 'High contrast cyan console glow with deep amber accretion backdrop',
          voiceover: 'Nothing escapes an event horizon. That was the first law they taught us at the orbital academy.',
          content: `INT. ASTRAEA COMMAND BRIDGE - DEEP SPACE NIGHT\n\nA vast curved panoramic canopy reveals the abyss: Cygnus X-1's accretion disk burns in blinding amber and electric violet, framing an impossibly pitch-black sphere that drinks all light.\n\nELENA VANCE (42), clad in pressurized mission flight-skin, taps a translucent console. Reflected starlight dances across her visor.\n\nELENA\nStatus on the perimeter buoy, IRIS. Is the drift within tolerance?\n\nIRIS (O.S.)\nDrift is nominal, Commander. However, antenna array 03 has registered a coherent anomaly along the photon boundary.`,
        },
        {
          id: 'scene-2',
          projectId: 'proj-unknown-signal',
          scriptId: 'script-astraea-signal',
          sceneNumber: 2,
          slugline: 'INT. SIGNAL ANALYSIS LABORATORY - CONTINUOUS',
          timeOfDay: 'DEEP VOID',
          summary: 'Dr. Thorne discovers that the signal contains human genetic base-pair codings.',
          dialogueCount: 6,
          characters: ['Elena Vance', 'Dr. Kenneth Thorne'],
          status: 'Draft',
          duration: '01:30',
          durationSec: 90,
          cameraDirection: 'Tracking Handheld',
          shotType: 'Medium Two-Shot',
          lightingMood: 'Dark lab with vivid green holographic phosphor nucleotide reflections',
          voiceover: 'Look at the prime intervals! It inserts genetic base-pair codings.',
          content: `INT. SIGNAL ANALYSIS LABORATORY - CONTINUOUS\n\nDR. THORNE's eyes are bloodshot, wide with an unhinged awe. Holographic waveform ribbons wrap around him like spiraling nebulae.\n\nTHORNE\nLook at the prime intervals! 2, 3, 5, 7, 11... but then it deviates. It inserts genetic base-pair codings.\n\nELENA\nHuman?\n\nTHORNE\nHuman base pairs, Vance! Broadcast from a stellar body that formed two billion years before our sun ignited.`,
        },
        {
          id: 'scene-3',
          projectId: 'proj-unknown-signal',
          scriptId: 'script-astraea-signal',
          sceneNumber: 3,
          slugline: 'EXT. EVENT HORIZON THRESHOLD - CONTINUOUS',
          timeOfDay: 'DEEP VOID',
          summary: 'The tether probe is launched into the gravitational well; spatiotemporal causality fractures.',
          dialogueCount: 4,
          characters: ['Elena Vance', 'IRIS'],
          status: 'Draft',
          duration: '01:20',
          durationSec: 80,
          cameraDirection: 'Extreme Wide Orbital Tracking',
          shotType: 'Extreme Wide',
          lightingMood: 'Blinding relativistic blueshift on event horizon photon sphere',
          voiceover: 'Telemetry delay is cascading: one second, four seconds, thirty seconds.',
          content: `EXT. EVENT HORIZON THRESHOLD - CONTINUOUS\n\nThe ASTRAEA fires a needle-thin titanium probe towards the absolute dark center.\n\nGravitational lensing bends the probe's exhaust plume into a surreal circle of light.\n\nIRIS\nTelemetry delay is exponentially expanding. 1 second... 4 seconds... 32 seconds. We are losing causal contact.`,
        },
      ],
      versions: [
        {
          versionNumber: 1,
          timestamp: '2026-09-18 10:15',
          title: 'Initial Autonomous Synthesis v1.0',
          sections: [],
          scenes: [],
          summaryNote: 'First complete draft synthesized from Ergosphere Broadcast idea and Astraea Story Bible.',
        },
      ],
      createdAt: '2026-09-18 09:30',
      updatedAt: '2026-09-18 10:15',
    },
  ],
  jobs: [
    {
      id: 'job-101',
      projectId: 'proj-unknown-signal',
      type: 'script-breakdown',
      status: 'Ready',
      input: { sceneRange: '1-3' },
      output: { totalShotsExtracted: 6, opticalDensity: 'High' },
      progress: 100,
      createdAt: '2026-09-17 11:30',
      updatedAt: '2026-09-17 11:32',
    },
    {
      id: 'job-102',
      projectId: 'proj-unknown-signal',
      type: 'audio-mix',
      status: 'Ready',
      input: { stems: ['voice', 'music', 'sfx'] },
      output: { masterWaveform: 'Loudness Integrated -14 LUFS' },
      progress: 100,
      createdAt: '2026-09-18 09:45',
      updatedAt: '2026-09-18 09:48',
    },
  ],
  seo: {
    title: 'UNKNOWN SIGNAL // The Impossible 1420 MHz Transmission from Cygnus X-1',
    description: 'Investigating a repeating anomalous signal originating from the photon sphere of Cygnus X-1. A cinematic sci-fi production.',
    keywords: ['Cygnus X-1', 'Astrophysics', 'Event Horizon', 'Sci-Fi Film', 'Deep Space', 'Dark Matter'],
    tags: ['astrophysics', 'blackhole', 'spaceexploration', 'scififilm', 'unknownsignal'],
    hashtags: ['#DeepSpace', '#Astrophysics', '#SciFiShort', '#DarkMatter'],
    category: 'Film & Animation',
    targetAudience: 'Sci-fi cinema enthusiasts, astronomy and cosmology community, science documentary viewers',
    hookRetentionAngle: 'Opening 5-second silence followed by sudden carrier frequency spike to maximize 30-second retention',
  },
  analytics: {
    estimatedViews: '350K - 1.2M',
    projectedRetention: '68.4% at 1:00',
    hookDropoffRate: '12.1% (Low)',
    audienceEngagementScore: 92,
    keywordSearchVolume: 'High (84/100)',
    viralPotential: 'Exceptional',
    telemetryNotes: [
      'High search intent on "Cygnus X-1 signal" and "event horizon paradox".',
      'Strong thumbnail contrast between dark void and cyan event horizon.',
      'Optimal publish window: Thursday 16:00 UTC.',
    ],
  },
  filmMode: {
    sourceTitle: 'Voyager IX Chronological Telemetry',
    sourceFormat: 'Movie',
    sourceStatus: 'INGESTED',
    tensionCurvePoints: [20, 45, 35, 70, 85, 60, 95, 40],
    cadenceBpm: 68,
    originalExplanationAngle: 'Investigative narrative deconstruction focusing on real-world Hawking radiation and gravitational red-shift physics.',
    seriesParts: [
      {
        partNumber: 1,
        title: 'The Intercept',
        synopsis: 'First detection on the outer perimeter listening post.',
        continuityNotes: 'Elena Vance is solo on bridge duty.',
      },
      {
        partNumber: 2,
        title: 'The Event Horizon Dilemma',
        synopsis: 'Deploying the gravitational tether probe into the singularity.',
        continuityNotes: 'IRIS detects internal clock drift.',
      },
    ],
    authorizedTransformationNotice: 'Authorized transformative analysis and original creative production pipeline.',
  },
  repurpose: {
    sourceScriptId: 'script-1',
    segments: [
      {
        id: 'rep-1',
        title: 'The Event Horizon Paradox',
        originalSceneRef: 'Scene 1',
        newHook: 'What happens when an SOS signal is emitted from inside a black hole?',
        contextRewrite: 'Quick 45-second explanation of photon sphere trapping and why this transmission breaks physics.',
        targetDuration: '00:45',
        aspectRatio: '9:16',
        status: 'Ready',
      },
      {
        id: 'rep-2',
        title: 'IRIS AI vs The Singularity',
        originalSceneRef: 'Scene 2',
        newHook: 'Can artificial intelligence survive infinite gravitational distortion?',
        contextRewrite: 'Deconstructing the tensor calculations required to maintain quantum coherence in zero-g.',
        targetDuration: '00:58',
        aspectRatio: '9:16',
        status: 'Polished',
      },
    ],
  },
  versionHistory: [
    {
      id: 'ver-1',
      projectId: 'proj-unknown-signal',
      version: '1.0.0',
      timestamp: '2026-09-15 08:24:00',
      changeType: 'CREATE',
      module: 'dashboard',
      description: 'Mission initialized on Dark Matter Command Bridge.',
    },
    {
      id: 'ver-2',
      projectId: 'proj-unknown-signal',
      version: '1.1.0',
      timestamp: '2026-09-16 14:10:00',
      changeType: 'BIBLE_UPDATE',
      module: 'bible',
      description: 'Codified core world rules: Relativistic time dilation factor 12.',
    },
    {
      id: 'ver-3',
      projectId: 'proj-unknown-signal',
      version: '1.2.0',
      timestamp: '2026-09-18 10:45:12',
      changeType: 'SCENE_EDIT',
      module: 'script',
      description: 'Completed Scene 1 screenplay dialogue and camera shot mappings.',
    },
  ],
};

export const INITIAL_TELEMETRY = {
  coreFrequency: '1420.405 MHz',
  gravityWarp: '0.084 G-WARP',
  darkMatterDensity: '98.42%',
  bufferOccupancy: 38,
  systemHealth: 99.8,
  activeNodes: 12,
  localAIStatus: 'READY' as const,
  aiCoreStatus: 'READY' as const,
};
